(function(root){
'use strict'
const Core=root.NestV202
if(!Core)throw new Error('NEST Datenspeicher konnte nicht geladen werden')
const RELEASE=Core.RELEASE
const EXPENSE_CATS=['Abos & Verträge','Lebensmittel','Wohnen','Mobilität','Freizeit','Shopping','Gesundheit','Haushalt','Sparen','Sonstiges']
const INCOME_CATS=['Gehalt','Bonus','Verkauf','Rückzahlung','Geschenk','Sonstiges']
const app=document.getElementById('app'),sheet=document.getElementById('sheet'),toast=document.getElementById('toast')
let state=Core.loadState(),route=Core.loadPrefs().startRoute||'overview'

const icons={
 overview:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M3 10.5 12 3l9 7.5"/><path d="M5 9.5V20h14V9.5"/><path d="M9 20v-6h6v6"/></svg>',
 transactions:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3z"/><path d="M9 8h6"/><path d="M9 12h6"/><path d="M9 16h4"/></svg>',
 add:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><path d="M12 5v14"/><path d="M5 12h14"/></svg>',
 goals:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="M12 12l6-6"/></svg>',
 challenges:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M8 21h8"/><path d="M12 17v4"/><path d="M7 4h10v4a5 5 0 0 1-10 0V4z"/><path d="M7 6H4a3 3 0 0 0 3 3"/><path d="M17 6h3a3 3 0 0 1-3 3"/></svg>'
}
function clone(v){if(typeof structuredClone==='function')return structuredClone(v);return JSON.parse(JSON.stringify(v))}
function n(v,d=0){const x=Number(v);return Number.isFinite(x)?x:d}
function clamp(v,min,max){return Math.min(max,Math.max(min,v))}
function esc(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function euro(v){return new Intl.NumberFormat('de-AT',{style:'currency',currency:'EUR'}).format(n(v))}
function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function formatDate(value){if(!value)return'–';const d=new Date(`${String(value).slice(0,10)}T12:00:00`);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('de-AT').format(d):String(value)}
function formatDateTime(value){if(!value)return'–';const d=new Date(value);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('de-AT',{dateStyle:'medium',timeStyle:'short'}).format(d):'–'}
function show(msg,isError=false){if(!toast)return;toast.textContent=msg;toast.classList.toggle('bad',isError);toast.classList.add('show');clearTimeout(show.t);show.t=setTimeout(()=>{toast.classList.remove('show','bad')},2400)}
function resolveTheme(){const p=Core.loadPrefs();if(p.appearance==='dark'||p.appearance==='light')return p.appearance;return matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}
function applyPreferences(){const p=Core.loadPrefs(),html=document.documentElement;html.dataset.theme=resolveTheme();html.dataset.nestAppearance=p.appearance;html.dataset.density=p.density;html.dataset.textSize=p.textSize;html.dataset.privacy=p.privacy?'on':'off';html.dataset.reduceMotion=p.reduceMotion?'on':'off';html.dataset.nestRelease=RELEASE}
function persist(mutator,message,method='manual'){
  const next=clone(state)
  try{mutator(next);state=Core.saveState(next,{method});render();if(message)show(message);return true}catch(error){console.error('NEST save failed',error);show('Speichern fehlgeschlagen – Daten wurden nicht übernommen',true);return false}
}
function summary(){let income=0,expense=0,totalIncome=0,totalExpense=0;const month=localDate().slice(0,7);for(const t of state.transactions){if(t.type==='income')totalIncome+=t.amount;else totalExpense+=t.amount;if(String(t.date).startsWith(month)){if(t.type==='income')income+=t.amount;else expense+=t.amount}}return{income,expense,balance:state.openingBalance+totalIncome-totalExpense}}
function audit(){return Core.readAudit()}
function eventsFor(id,a=audit()){return Core.eventsFor(id,a)}
function sourceFor(tx,a=audit()){return Core.latestMethod(tx.id,a,tx)}
function sourceLabel(method){return method==='wallet'?'Wallet':method==='manual'?'Manuell':method==='legacy'?'Übernommen':'System'}
function sourceClass(method){return['wallet','manual','legacy'].includes(method)?method:'system'}
function createdAtFor(tx,a=audit()){const e=eventsFor(tx.id,a).find(x=>x.action==='created'||x.action==='migrated');return e?.originalAt||e?.at||(tx.createdAt?new Date(tx.createdAt).toISOString():null)}
function repeatsFor(tx){const sig=Core.transactionSignature(tx);return state.transactions.filter(x=>Core.transactionSignature(x)===sig).sort((a,b)=>String(b.date).localeCompare(String(a.date))||b.createdAt-a.createdAt)}
function top(){const title={overview:'Übersicht',transactions:'Buchungen',goals:'Sparziele',challenges:'Challenges'}[route]||'NEST';return `<header class="top"><div><span class="eyebrow">NEST ${esc(RELEASE)} · ${esc(new Intl.DateTimeFormat('de-AT',{month:'long',year:'numeric'}).format(new Date()).toUpperCase())}</span><h1>${title}</h1></div><button class="icon-btn" data-action="settings" aria-label="Einstellungen">⋯</button></header>`}
function navButton(r,label){return `<button type="button" data-route="${r}" class="${route===r?'active':''}"><b class="v2-nav-icon" aria-hidden="true">${icons[r]}</b><span>${label}</span></button>`}
function tabs(){return `<nav class="tabs v2-nav-centered" aria-label="Hauptnavigation"><div class="v2-nav-brand"><div>N</div><span><b>NEST</b><small>Finance Workspace</small></span></div>${navButton('overview','Übersicht')}${navButton('transactions','Buchungen')}<button type="button" class="v2-center-add" data-action="add-tx" aria-label="Neue manuelle Buchung"><span class="v2-center-add-icon" aria-hidden="true">${icons.add}</span><span class="v2-center-add-copy"><b>Neue Buchung</b><small>Manuell erfassen</small></span></button>${navButton('goals','Sparziele')}${navButton('challenges','Challenges')}<div class="v2-nav-foot"><span>Web & Mobile</span><b>v${esc(RELEASE)}</b></div></nav>`}
function render(){applyPreferences();let body=route==='overview'?overview():route==='transactions'?transactions():route==='goals'?goals():challenges();app.innerHTML=`<div class="shell">${top()}${body}</div>${tabs()}`;document.documentElement.setAttribute('data-app-ready','true');root.__SELFMADE_READY__=true}
function overview(){const s=summary(),recent=[...state.transactions].sort((a,b)=>String(b.date).localeCompare(String(a.date))||b.createdAt-a.createdAt).slice(0,5);return `<section class="hero"><small>Aktueller Stand</small><strong>${euro(s.balance)}</strong><div class="hero-row"><div class="mini"><span>Einzahlungen</span><b>${euro(s.income)}</b></div><div class="mini"><span>Auszahlungen</span><b>${euro(s.expense)}</b></div></div></section><div class="section-head"><div><h2>Zuletzt</h2><p>Deine neuesten Buchungen</p></div><button class="link-btn" data-route="transactions">Alle</button></div><div class="card list">${recent.length?recent.map(txRow).join(''):'<div class="empty"><b>Noch keine Buchungen</b>Mit dem Plus unten kannst du deine erste Buchung anlegen.</div>'}</div><div class="section-head"><div><h2>Aktive Ziele</h2><p>Sparen mit sichtbarem Fortschritt</p></div><button class="link-btn" data-route="goals">Öffnen</button></div><div class="card">${state.goals.length?state.goals.slice(0,2).map(goalCard).join(''):'<div class="empty"><b>Noch kein Sparziel</b>Lege dein erstes Ziel an.</div>'}</div>`}
function txRow(t){const a=audit(),method=sourceFor(t,a),repeat=repeatsFor(t).length,stamp=createdAtFor(t,a);return `<button type="button" class="row v2-tx-row" data-action="tx-detail" data-id="${esc(t.id)}"><div class="row-main"><strong>${esc(t.title)}</strong><small>${esc(t.category)} · ${esc(formatDate(t.date))}</small><span class="v2-booking-meta"><i class="v2-method ${sourceClass(method)}">${sourceLabel(method)}</i><span>${esc(formatDateTime(stamp))}</span>${repeat>1?`<i class="v2-repeat">${repeat}× verbucht</i>`:''}</span></div><span class="amount ${t.type==='income'?'good':'bad'}">${t.type==='income'?'+':'−'} ${euro(t.amount)}</span></button>`}
function ledgerSummary(){const a=audit(),txs=state.transactions,wallet=txs.filter(tx=>sourceFor(tx,a)==='wallet').length,manual=txs.filter(tx=>sourceFor(tx,a)==='manual').length,groups=new Map();txs.forEach(tx=>{const s=Core.transactionSignature(tx);groups.set(s,(groups.get(s)||0)+1)});const recurring=[...groups.values()].filter(v=>v>1).length;return `<section class="v2-ledger-summary"><div class="v2-ledger-title"><div><span>BUCHUNGSZENTRALE</span><h2>Nachvollziehbar verbucht</h2><p>Quelle, Zeitpunkt und Änderungen bleiben im Protokoll erhalten.</p></div><button type="button" data-action="audit">Protokoll öffnen</button></div><div class="v2-ledger-stats"><div><small>Gesamt</small><b>${txs.length}</b></div><div><small>Wallet</small><b>${wallet}</b></div><div><small>Manuell</small><b>${manual}</b></div><div><small>Wiederkehrend</small><b>${recurring}</b></div></div></section>`}
function transactions(){const items=[...state.transactions].sort((a,b)=>String(b.date).localeCompare(String(a.date))||b.createdAt-a.createdAt);return `<div class="section-head"><div><h2>Alle Buchungen</h2><p>Einzahlungen und Auszahlungen mit Historie</p></div><button class="link-btn" data-action="add-tx">+ Neu</button></div>${ledgerSummary()}<div class="card list">${items.length?items.map(txRow).join(''):'<div class="empty"><b>Noch leer</b>Lege eine Buchung manuell an oder importiere sie über Wallet.</div>'}</div>`}
function goalCard(g){const pct=g.target?Math.round(clamp(g.saved/g.target,0,1)*100):0;return `<div class="goal"><div class="goal-top"><div><h3>${esc(g.name)}</h3><p>${euro(g.saved)} von ${euro(g.target)}${g.deadline?` · bis ${esc(formatDate(g.deadline))}`:''}</p></div><span class="pill">${pct}%</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="goal-actions"><button class="small-btn primary" data-action="goal-money" data-id="${esc(g.id)}" data-dir="add">+ Sparen</button><button class="small-btn" data-action="goal-money" data-id="${esc(g.id)}" data-dir="remove">Entnehmen</button><button class="small-btn" data-action="edit-goal" data-id="${esc(g.id)}">Bearbeiten</button></div></div>`}
function goals(){return `<div class="section-head"><div><h2>Deine Sparziele</h2><p>Fortschritt und Zielbetrag verwalten</p></div><button class="link-btn" data-action="add-goal">+ Ziel</button></div><div class="card">${state.goals.length?state.goals.map(goalCard).join(''):'<div class="empty"><b>Noch kein Sparziel</b>Erstelle dein erstes Sparziel.</div>'}</div>`}
function challengeProgress(c){const pct=c.steps?Math.round(clamp(c.completed/c.steps,0,1)*100):0;return{pct,saved:c.steps?c.target*(c.completed/c.steps):0}}
function challengeCard(c){const p=challengeProgress(c);return `<div class="challenge"><div class="challenge-top"><div><h3>${esc(c.name)}</h3><p>${c.custom?'Eigene Challenge':'NEST Vorlage'}${c.deadline?` · bis ${esc(formatDate(c.deadline))}`:''}</p></div><span class="pill">${p.pct}%</span></div><div class="progress"><i style="width:${p.pct}%"></i></div><div class="meta"><span>${c.completed}/${c.steps} Schritte</span><span>${euro(p.saved)} / ${euro(c.target)}</span></div><div class="challenge-actions"><button class="small-btn primary" data-action="challenge-step" data-id="${esc(c.id)}" data-dir="1" ${c.completed>=c.steps?'disabled':''}>Schritt +</button><button class="small-btn" data-action="challenge-step" data-id="${esc(c.id)}" data-dir="-1" ${c.completed<=0?'disabled':''}>Zurück</button>${c.custom?`<button class="small-btn" data-action="edit-challenge" data-id="${esc(c.id)}">Bearbeiten</button>`:''}</div></div>`}
function challenges(){return `<div class="section-head"><div><h2>Spar-Challenges</h2><p>Vorlagen oder eigene Challenges</p></div><button class="link-btn" data-action="add-challenge">+ Eigene</button></div><div class="card">${state.challenges.length?state.challenges.map(challengeCard).join(''):'<div class="empty"><b>Keine Challenges</b>Erstelle eine eigene Challenge.</div>'}</div>`}
function openSheet(html){sheet.innerHTML=html;if(!sheet.open)sheet.showModal()}
function closeSheet(){if(sheet.open)sheet.close();sheet.innerHTML=''}
function sheetWrap(title,eyebrow,body,{form='',id='',label='Speichern',left=''}){return `<form class="sheet v2-form" data-form="${form}" data-id="${esc(id)}"><div class="handle"></div><header><div><span class="eyebrow">${esc(eyebrow)}</span><h2>${esc(title)}</h2></div><button type="button" class="close" data-action="close" aria-label="Schließen">×</button></header><div class="sheet-body"><div class="v2-form-intro"><span>NEST V${esc(RELEASE)}</span><b>${esc(title)}</b><p>Daten werden erst nach erfolgreicher Speicherprüfung übernommen.</p></div>${body}</div><footer>${left}<button class="btn primary" type="submit">${esc(label)}</button></footer></form>`}
function categoryOptions(type,current=''){const list=type==='income'?INCOME_CATS:EXPENSE_CATS;return list.map(c=>`<option value="${esc(c)}" ${c===current?'selected':''}>${esc(c)}</option>`).join('')}
function txSheet(id=''){const t=id?state.transactions.find(x=>x.id===id):null,type=t?.type||'expense';openSheet(sheetWrap(t?'Buchung bearbeiten':'Neue Buchung','BUCHUNG',`<label class="v2-field">Art<select name="type"><option value="expense" ${type==='expense'?'selected':''}>Auszahlung</option><option value="income" ${type==='income'?'selected':''}>Einzahlung</option></select></label><label class="v2-field">Betrag<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" required value="${t?.amount||''}" placeholder="0,00"></label><label class="v2-field">Wofür / von wem?<input name="title" required maxlength="80" value="${esc(t?.title||'')}" placeholder="z. B. BILLA, Netflix, Gehalt"></label><label class="v2-field">Kategorie<select name="category">${categoryOptions(type,t?.category||'')}</select></label><label class="v2-field">Datum<input name="date" type="date" required value="${esc(t?.date||localDate())}"></label><label class="v2-field">Notiz<textarea name="note" maxlength="180" placeholder="Optional">${esc(t?.note||'')}</textarea></label>`,{form:'transaction',id:t?.id||'',label:t?'Änderungen speichern':'Buchung anlegen',left:t?`<button type="button" class="btn danger" data-action="delete-tx" data-id="${esc(t.id)}">Löschen</button>`:''}))}
function goalSheet(id=''){const g=id?state.goals.find(x=>x.id===id):null;openSheet(sheetWrap(g?'Sparziel bearbeiten':'Neues Sparziel','SPARZIEL',`<label class="v2-field">Name<input name="name" required maxlength="60" value="${esc(g?.name||'')}" placeholder="z. B. Urlaub"></label><label class="v2-field">Zielbetrag<input name="target" type="number" min="1" step="0.01" inputmode="decimal" required value="${g?.target||''}"></label><label class="v2-field">Zieldatum<input name="deadline" type="date" value="${esc(g?.deadline||'')}"></label>`,{form:'goal',id:g?.id||'',label:g?'Speichern':'Ziel erstellen',left:g?`<button type="button" class="btn danger" data-action="delete-goal" data-id="${esc(g.id)}">Löschen</button>`:''}))}
function challengeSheet(id=''){const c=id?state.challenges.find(x=>x.id===id):null;openSheet(sheetWrap(c?'Challenge bearbeiten':'Eigene Challenge','CHALLENGE',`<label class="v2-field">Name<input name="name" required maxlength="70" value="${esc(c?.name||'')}"></label><label class="v2-field">Zielbetrag<input name="target" type="number" min="1" step="0.01" inputmode="decimal" required value="${c?.target||''}"></label><label class="v2-field">Schritte<input name="steps" type="number" min="1" max="365" step="1" required value="${c?.steps||12}"></label><label class="v2-field">Zieldatum<input name="deadline" type="date" value="${esc(c?.deadline||'')}"></label>`,{form:'challenge',id:c?.id||'',label:c?'Speichern':'Challenge erstellen',left:c?`<button type="button" class="btn danger" data-action="delete-challenge" data-id="${esc(c.id)}">Löschen</button>`:''}))}
function moneySheet(id,dir){const g=state.goals.find(x=>x.id===id);if(!g)return;openSheet(sheetWrap(dir==='add'?'Zum Ziel sparen':'Vom Ziel entnehmen',g.name,`<label class="v2-field">Betrag<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" required autofocus></label><input type="hidden" name="dir" value="${dir}">`,{form:'goal-money',id,label:dir==='add'?'Hinzufügen':'Entnehmen'}))}
function ensureDialog(id,label){let d=document.getElementById(id);if(!d){d=document.createElement('dialog');d.id=id;d.className='v2-dialog';d.setAttribute('aria-label',label);document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d)d.close()})}return d}
function eventText(e){if(e.action==='created')return e.method==='wallet'?'Über Apple Wallet / Kurzbefehle verbucht':'Manuell in NEST verbucht';if(e.action==='migrated')return e.method==='wallet'?'Wallet-Buchung aus älterer Version übernommen':'Aus älterer NEST-Version übernommen';if(e.action==='updated')return e.changes?.length?`Geändert: ${e.changes.join(', ')}`:'Buchung geändert';if(e.action==='deleted')return'Buchung gelöscht';return'Buchung aktualisiert'}
function txDetail(id){const tx=state.transactions.find(x=>x.id===id);if(!tx)return;const a=audit(),method=sourceFor(tx,a),matches=repeatsFor(tx),events=eventsFor(id,a),d=ensureDialog('v202Transaction','Buchungsdetails');d.innerHTML=`<article class="v2-detail-shell"><header class="v2-detail-head"><div><span>VERBUCHTE TRANSAKTION</span><h2>${esc(tx.title)}</h2><p>${esc(tx.category)}</p></div><button type="button" data-dialog-close aria-label="Schließen">×</button></header><section class="v2-detail-amount ${tx.type}"><small>${tx.type==='income'?'Einzahlung':'Auszahlung'}</small><strong>${tx.type==='income'?'+':'−'} ${euro(tx.amount)}</strong><em>Verbucht</em></section><section class="v2-facts"><div><span>Buchungsdatum</span><b>${esc(formatDate(tx.date))}</b></div><div><span>Erfasst am</span><b>${esc(formatDateTime(createdAtFor(tx,a)))}</b></div><div><span>Verbucht über</span><b>${esc(Core.methodLabel(method))}</b></div><div><span>Status</span><b>Verbucht</b></div></section>${tx.note?`<section class="v2-note"><span>Notiz</span><p>${esc(tx.note)}</p></section>`:''}${matches.length>1?`<div class="v2-repeat-box"><div><span>Bereits verbucht</span><b>${matches.length}× mit gleichem Betrag und Verwendungszweck</b></div><div class="v2-repeat-list">${matches.slice(0,8).map(x=>`<span>${esc(formatDate(x.date))}<b>${euro(x.amount)}</b></span>`).join('')}</div></div>`:''}<section class="v2-history"><div class="v2-section-title"><span>Buchungsverlauf</span><p>Wann und wie diese Buchung erfasst oder geändert wurde.</p></div>${events.length?events.slice(0,20).map(e=>`<div class="v2-timeline-item"><i class="${sourceClass(e.method)}"></i><div><b>${esc(eventText(e))}</b><small>${esc(formatDateTime(e.at))} · ${esc(Core.methodLabel(e.method))}</small></div></div>`).join(''):'<div class="v2-empty-history">Noch kein Protokoll vorhanden.</div>'}</section><footer class="v2-detail-actions"><button type="button" class="secondary" data-dialog-close>Schließen</button><button type="button" class="primary" data-edit-tx="${esc(tx.id)}">Buchung bearbeiten</button></footer></article>`;d.showModal()}
function auditDialog(){const events=[...audit().events].sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,250),d=ensureDialog('v202Audit','Buchungsprotokoll');d.innerHTML=`<article class="v2-audit-shell"><header class="v2-detail-head"><div><span>NEST V${esc(RELEASE)}</span><h2>Buchungsprotokoll</h2><p>Erstellungen, Änderungen und Löschungen.</p></div><button type="button" data-dialog-close>×</button></header><div class="v2-audit-list">${events.length?events.map(e=>{const s=e.snapshot||{};return `<div class="v2-audit-row"><div class="v2-audit-icon ${sourceClass(e.method)}"></div><div class="v2-audit-main"><strong>${esc(s.title||'Buchung')}</strong><span>${esc(eventText(e))}</span><small>${esc(formatDateTime(e.at))} · ${esc(Core.methodLabel(e.method))}</small></div><b>${s.amount!=null?euro(s.amount):''}</b></div>`}).join(''):'<div class="v2-empty-history">Noch keine Protokolleinträge.</div>'}</div><footer class="v2-detail-actions"><button type="button" class="primary" data-dialog-close>Fertig</button></footer></article>`;d.showModal()}

app.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-route]');if(!b)return;if(b.dataset.route){route=b.dataset.route;render();return}const a=b.dataset.action;if(a==='add-tx')txSheet();else if(a==='tx-detail')txDetail(b.dataset.id);else if(a==='audit')auditDialog();else if(a==='add-goal')goalSheet();else if(a==='edit-goal')goalSheet(b.dataset.id);else if(a==='add-challenge')challengeSheet();else if(a==='edit-challenge')challengeSheet(b.dataset.id);else if(a==='goal-money')moneySheet(b.dataset.id,b.dataset.dir);else if(a==='challenge-step')persist(s=>{const c=s.challenges.find(x=>x.id===b.dataset.id);if(c)c.completed=clamp(c.completed+n(b.dataset.dir),0,c.steps)},'Challenge aktualisiert')})
sheet.addEventListener('click',e=>{if(e.target===sheet){closeSheet();return}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='close')closeSheet();else if(a==='delete-tx'&&confirm('Buchung wirklich löschen?')){if(persist(s=>{s.transactions=s.transactions.filter(x=>x.id!==b.dataset.id)},'Buchung gelöscht'))closeSheet()}else if(a==='delete-goal'&&confirm('Sparziel wirklich löschen?')){if(persist(s=>{s.goals=s.goals.filter(x=>x.id!==b.dataset.id)},'Sparziel gelöscht'))closeSheet()}else if(a==='delete-challenge'&&confirm('Challenge wirklich löschen?')){if(persist(s=>{s.challenges=s.challenges.filter(x=>x.id!==b.dataset.id)},'Challenge gelöscht'))closeSheet()}})
sheet.addEventListener('change',e=>{if(e.target?.name!=='type')return;const select=sheet.querySelector('select[name="category"]');if(!select)return;const type=e.target.value,current=select.value,list=type==='income'?INCOME_CATS:EXPENSE_CATS;select.innerHTML=categoryOptions(type,list.includes(current)?current:list[0])})
sheet.addEventListener('submit',e=>{e.preventDefault();const f=e.target.closest('form[data-form]');if(!f)return;const d=new FormData(f),kind=f.dataset.form,id=f.dataset.id;let ok=false;if(kind==='transaction'){const existing=id?state.transactions.find(x=>x.id===id):null,amount=n(d.get('amount'));if(amount<=0){show('Bitte einen gültigen Betrag eingeben',true);return}const tx=Core.normalizeTransaction({id:id||undefined,type:d.get('type'),amount,title:d.get('title'),category:d.get('category'),date:d.get('date'),note:d.get('note'),createdAt:existing?.createdAt||Date.now(),updatedAt:Date.now(),source:existing?.source||'manual'});ok=persist(s=>{const i=s.transactions.findIndex(x=>x.id===id);if(i>=0)s.transactions[i]=tx;else s.transactions.push(tx)},id?'Buchung gespeichert':'Buchung angelegt')}else if(kind==='goal'){const old=id?state.goals.find(x=>x.id===id):null,data=Core.normalizeGoal({id:id||undefined,name:d.get('name'),target:d.get('target'),saved:old?.saved||0,deadline:d.get('deadline'),createdAt:old?.createdAt||Date.now()});ok=persist(s=>{const i=s.goals.findIndex(x=>x.id===id);if(i>=0)s.goals[i]=data;else s.goals.push(data)},id?'Sparziel gespeichert':'Sparziel erstellt')}else if(kind==='goal-money'){const amount=Math.max(0,n(d.get('amount'))),dir=String(d.get('dir'));if(amount<=0){show('Bitte einen gültigen Betrag eingeben',true);return}ok=persist(s=>{const g=s.goals.find(x=>x.id===id);if(g)g.saved=Math.max(0,g.saved+(dir==='add'?amount:-amount))},dir==='add'?'Sparbetrag hinzugefügt':'Betrag entnommen')}else if(kind==='challenge'){const old=id?state.challenges.find(x=>x.id===id):null,c=Core.normalizeChallenge({id:id||undefined,name:d.get('name'),target:d.get('target'),steps:d.get('steps'),completed:old?.completed||0,deadline:d.get('deadline'),custom:true,createdAt:old?.createdAt||Date.now()});ok=persist(s=>{const i=s.challenges.findIndex(x=>x.id===id);if(i>=0)s.challenges[i]=c;else s.challenges.push(c)},id?'Challenge gespeichert':'Challenge erstellt')}if(ok)closeSheet()})
document.addEventListener('click',e=>{const close=e.target.closest('[data-dialog-close]');if(close){close.closest('dialog')?.close();return}const edit=e.target.closest('[data-edit-tx]');if(edit){edit.closest('dialog')?.close();txSheet(edit.dataset.editTx)}})
window.addEventListener('storage',e=>{if(e.key===Core.CORE_KEY){state=Core.loadState();render()}if(e.key===Core.PREF_KEY)applyPreferences()})
window.addEventListener('pageshow',e=>{if(e.persisted){state=Core.loadState();render()}})
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(console.warn))
applyPreferences();render();const health=Core.status();if(!health.available)setTimeout(()=>show('Lokaler Datenspeicher ist nicht verfügbar',true),300)
root.NestAppV202={render,reload(){state=Core.loadState();render()},openTransaction:txDetail}
})(globalThis)
