(function(root){
'use strict'
const VERSION='1.2.0', STORAGE_KEY='selfmade-save-v1'
const EXPENSE_CATS=['Abos & Verträge','Lebensmittel','Wohnen','Mobilität','Freizeit','Shopping','Gesundheit','Haushalt','Sparen','Sonstiges']
const INCOME_CATS=['Gehalt','Bonus','Verkauf','Rückzahlung','Geschenk','Sonstiges']
function uid(p='id'){return `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,9)}`}
function n(v,d=0){v=Number(v);return Number.isFinite(v)?v:d}
function clamp(v,min,max){return Math.min(max,Math.max(min,v))}
function initialState(){return{version:VERSION,openingBalance:0,transactions:[],goals:[],challenges:[],settings:{onboarded:true,theme:'light'}}}
function normalizeTransaction(x={}){return{id:String(x.id||uid('tx')),type:x.type==='income'?'income':'expense',amount:Math.max(0,n(x.amount)),title:String(x.title||x.description||x.name||'Buchung').slice(0,80),category:String(x.category||'Sonstiges').slice(0,50),date:String(x.date||new Date().toISOString().slice(0,10)).slice(0,10),note:String(x.note||'').slice(0,180),createdAt:n(x.createdAt,Date.now())}}
function normalizeGoal(x={}){return{id:String(x.id||uid('goal')),name:String(x.name||'Sparziel').slice(0,60),target:Math.max(0,n(x.target||x.targetAmount)),saved:Math.max(0,n(x.saved||x.currentAmount)),deadline:x.deadline?String(x.deadline).slice(0,10):'',createdAt:n(x.createdAt,Date.now())}}
function normalizeChallenge(x={}){const target=Math.max(0,n(x.target||x.targetAmount||x.total));const steps=Math.max(1,Math.round(n(x.steps||x.totalSteps,20)));const completed=Math.max(0,Math.min(steps,Math.round(n(x.completed||x.completedSteps,Array.isArray(x.doneSteps)?x.doneSteps.length:0))));return{id:String(x.id||uid('challenge')),name:String(x.name||x.title||'Challenge').slice(0,70),target,steps,completed,deadline:x.deadline?String(x.deadline).slice(0,10):'',custom:Boolean(x.custom),createdAt:n(x.createdAt,Date.now())}}
function defaultChallenges(){return[
{id:'builtin_52',name:'52-Wochen-Challenge',target:1378,steps:52,completed:0,deadline:'',custom:false,createdAt:Date.now()},
{id:'builtin_30x5',name:'30 Tage × 5 €',target:150,steps:30,completed:0,deadline:'',custom:false,createdAt:Date.now()},
{id:'builtin_1000',name:'1.000-€-Challenge',target:1000,steps:20,completed:0,deadline:'',custom:false,createdAt:Date.now()}
]}
function normalizeState(raw){const s=raw&&typeof raw==='object'?raw:{};let challenges=Array.isArray(s.challenges)?s.challenges.map(normalizeChallenge):[];if(!challenges.length)challenges=defaultChallenges();return{version:VERSION,openingBalance:n(s.openingBalance),transactions:Array.isArray(s.transactions)?s.transactions.map(normalizeTransaction):[],goals:Array.isArray(s.goals)?s.goals.map(normalizeGoal):[],challenges,settings:{onboarded:true,theme:['dark','light'].includes(s.settings?.theme)?s.settings.theme:'light'}}}
function challengeProgress(c){const percent=c.steps?Math.round(clamp(c.completed/c.steps,0,1)*100):0;const saved=c.steps?c.target*(c.completed/c.steps):0;return{percent,saved,remaining:Math.max(0,c.target-saved)}}
function createCustomChallenge({name,target,steps,deadline=''}){return normalizeChallenge({id:uid('challenge'),name,target,steps,completed:0,deadline,custom:true,createdAt:Date.now()})}
function summary(state,month=new Date().toISOString().slice(0,7)){let income=0,expense=0;for(const t of state.transactions){if(!String(t.date).startsWith(month))continue;if(t.type==='income')income+=t.amount;else expense+=t.amount}const totalIncome=state.transactions.filter(t=>t.type==='income').reduce((a,t)=>a+t.amount,0),totalExpense=state.transactions.filter(t=>t.type==='expense').reduce((a,t)=>a+t.amount,0);return{income,expense,net:income-expense,balance:state.openingBalance+totalIncome-totalExpense}}
root.NestLogic={VERSION,STORAGE_KEY,initialState,normalizeState,normalizeChallenge,challengeProgress,createCustomChallenge,summary}
if(typeof document==='undefined')return
const app=document.getElementById('app'),sheet=document.getElementById('sheet'),toast=document.getElementById('toast')
let state=load(),route='overview'
function load(){try{return normalizeState(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch{return initialState()}}
function save(){state.version=VERSION;localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function euro(v){return new Intl.NumberFormat('de-AT',{style:'currency',currency:'EUR'}).format(n(v))}
function esc(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function show(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(show.t);show.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function mutate(fn,msg){fn(state);save();render();if(msg)show(msg)}
function monthLabel(){return new Intl.DateTimeFormat('de-AT',{month:'long',year:'numeric'}).format(new Date())}
function top(){return `<header class="top"><div><span class="eyebrow">NEST · ${esc(monthLabel().toUpperCase())}</span><h1>${route==='overview'?'Übersicht':route==='transactions'?'Buchungen':route==='goals'?'Sparziele':'Challenges'}</h1></div><button class="icon-btn" data-action="settings" aria-label="Einstellungen">⋯</button></header>`}
function tabs(){return `<nav class="tabs"><button data-route="overview" class="${route==='overview'?'active':''}"><b>⌂</b>Übersicht</button><button data-route="transactions" class="${route==='transactions'?'active':''}"><b>↕</b>Buchungen</button><button data-route="goals" class="${route==='goals'?'active':''}"><b>◎</b>Sparziele</button><button data-route="challenges" class="${route==='challenges'?'active':''}"><b>◇</b>Challenges</button></nav>`}
function render(){document.documentElement.dataset.theme=state.settings.theme;let body='';if(route==='overview')body=overview();if(route==='transactions')body=transactions();if(route==='goals')body=goals();if(route==='challenges')body=challenges();app.innerHTML=`<div class="shell">${top()}${body}</div>${route!=='overview'?'<button class="fab" data-action="primary-add" aria-label="Hinzufügen">+</button>':''}${tabs()}`;document.documentElement.setAttribute('data-app-ready','true');root.__SELFMADE_READY__=true}
function overview(){const s=summary(state);const recent=[...state.transactions].sort((a,b)=>String(b.date).localeCompare(String(a.date))||b.createdAt-a.createdAt).slice(0,4);return `<section class="hero"><small>Aktueller Stand</small><strong>${euro(s.balance)}</strong><div class="hero-row"><div class="mini"><span>Einzahlungen</span><b>${euro(s.income)}</b></div><div class="mini"><span>Auszahlungen</span><b>${euro(s.expense)}</b></div></div></section><div class="section-head"><div><h2>Zuletzt</h2><p>Deine neuesten manuellen Buchungen</p></div><button class="link-btn" data-route="transactions">Alle</button></div><div class="card list">${recent.length?recent.map(txRow).join(''):'<div class="empty"><b>Noch keine Buchungen</b>Trage Einnahmen und Ausgaben manuell ein.</div>'}</div><div class="section-head"><div><h2>Aktive Ziele</h2><p>Sparen mit sichtbarem Fortschritt</p></div><button class="link-btn" data-route="goals">Öffnen</button></div><div class="card">${state.goals.length?state.goals.slice(0,2).map(goalCard).join(''):'<div class="empty"><b>Noch kein Sparziel</b>Lege dein erstes Ziel an.</div>'}</div>`}
function txRow(t){return `<div class="row" data-action="edit-tx" data-id="${esc(t.id)}"><div class="row-main"><strong>${esc(t.title)}</strong><small>${esc(t.category)} · ${esc(new Intl.DateTimeFormat('de-AT').format(new Date(t.date+'T12:00:00')))}</small></div><span class="amount ${t.type==='income'?'good':'bad'}">${t.type==='income'?'+':'−'} ${euro(t.amount)}</span></div>`}
function transactions(){const items=[...state.transactions].sort((a,b)=>String(b.date).localeCompare(String(a.date))||b.createdAt-a.createdAt);return `<div class="section-head"><div><h2>Alle Buchungen</h2><p>Ein- und Auszahlungen vollständig manuell</p></div><button class="link-btn" data-action="add-tx">+ Neu</button></div><div class="card list">${items.length?items.map(txRow).join(''):'<div class="empty"><b>Noch leer</b>Erfasse z. B. Gehalt, Netflix, Miete oder Einkauf.</div>'}</div>`}
function goalCard(g){const pct=g.target?Math.round(clamp(g.saved/g.target,0,1)*100):0;return `<div class="goal"><div class="goal-top"><div><h3>${esc(g.name)}</h3><p>${euro(g.saved)} von ${euro(g.target)}${g.deadline?` · bis ${esc(g.deadline)}`:''}</p></div><span class="pill">${pct}%</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="goal-actions"><button class="small-btn primary" data-action="goal-money" data-id="${esc(g.id)}" data-dir="add">+ Sparen</button><button class="small-btn" data-action="goal-money" data-id="${esc(g.id)}" data-dir="remove">Entnehmen</button><button class="small-btn" data-action="edit-goal" data-id="${esc(g.id)}">Bearbeiten</button></div></div>`}
function goals(){return `<div class="section-head"><div><h2>Deine Sparziele</h2><p>Für Urlaub, Rücklage oder jeden eigenen Wunsch</p></div><button class="link-btn" data-action="add-goal">+ Ziel</button></div><div class="card">${state.goals.length?state.goals.map(goalCard).join(''):'<div class="empty"><b>Noch kein Sparziel</b>Erstelle ein Ziel und buche Beträge manuell darauf.</div>'}</div>`}
function challengeCard(c){const p=challengeProgress(c);return `<div class="challenge"><div class="challenge-top"><div><h3>${esc(c.name)}</h3><p>${c.custom?'Eigene Challenge':'NEST Vorlage'}${c.deadline?` · bis ${esc(c.deadline)}`:''}</p></div><span class="pill">${p.percent}%</span></div><div class="progress"><i style="width:${p.percent}%"></i></div><div class="meta"><span>${c.completed}/${c.steps} Schritte</span><span>${euro(p.saved)} / ${euro(c.target)}</span></div><div class="challenge-actions"><button class="small-btn primary" data-action="challenge-step" data-id="${esc(c.id)}" data-dir="1" ${c.completed>=c.steps?'disabled':''}>Schritt +</button><button class="small-btn" data-action="challenge-step" data-id="${esc(c.id)}" data-dir="-1" ${c.completed<=0?'disabled':''}>Zurück</button>${c.custom?`<button class="small-btn" data-action="edit-challenge" data-id="${esc(c.id)}">Bearbeiten</button>`:''}</div></div>`}
function challenges(){return `<div class="section-head"><div><h2>Spar-Challenges</h2><p>Vorlagen nutzen oder komplett eigene Challenges erstellen</p></div><button class="link-btn" data-action="add-challenge">+ Eigene</button></div><div class="card">${state.challenges.map(challengeCard).join('')}</div>`}
function openSheet(html){sheet.innerHTML=html;sheet.showModal()}
function closeSheet(){if(sheet.open)sheet.close()}
function sheetWrap(title,eyebrow,body,footer){return `<form class="sheet" data-form="${footer.form||''}" data-id="${footer.id||''}"><div class="handle"></div><header><div><span class="eyebrow">${esc(eyebrow)}</span><h2>${esc(title)}</h2></div><button type="button" class="close" data-action="close">×</button></header><div class="sheet-body">${body}</div><footer>${footer.left||''}<button class="btn primary" type="submit">${esc(footer.label||'Speichern')}</button></footer></form>`}
function txSheet(id=''){const t=id?state.transactions.find(x=>x.id===id):null;const type=t?.type||'expense',cats=type==='income'?INCOME_CATS:EXPENSE_CATS;openSheet(sheetWrap(t?'Buchung bearbeiten':'Neue Buchung','MANUELL',`<label>Art<select name="type"><option value="expense" ${type==='expense'?'selected':''}>Auszahlung</option><option value="income" ${type==='income'?'selected':''}>Einzahlung</option></select></label><label>Betrag<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" required value="${t?.amount||''}" placeholder="0,00"></label><label>Wofür / von wem?<input name="title" required maxlength="80" value="${esc(t?.title||'')}" placeholder="z. B. Netflix, Miete, Gehalt"></label><label>Kategorie<select name="category">${cats.map(c=>`<option ${t?.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Datum<input name="date" type="date" required value="${esc(t?.date||new Date().toISOString().slice(0,10))}"></label><label>Notiz<textarea name="note" maxlength="180" placeholder="Optional">${esc(t?.note||'')}</textarea></label>`,{form:'transaction',id:t?.id||'',label:t?'Speichern':'Buchung anlegen',left:t?`<button type="button" class="btn danger" data-action="delete-tx" data-id="${esc(t.id)}">Löschen</button>`:''}))}
function goalSheet(id=''){const g=id?state.goals.find(x=>x.id===id):null;openSheet(sheetWrap(g?'Sparziel bearbeiten':'Neues Sparziel','SPARZIEL',`<label>Name<input name="name" required maxlength="60" value="${esc(g?.name||'')}" placeholder="z. B. Urlaub"></label><label>Zielbetrag<input name="target" type="number" min="1" step="0.01" inputmode="decimal" required value="${g?.target||''}" placeholder="1000"></label><label>Zieldatum<input name="deadline" type="date" value="${esc(g?.deadline||'')}"></label>`,{form:'goal',id:g?.id||'',label:g?'Speichern':'Ziel erstellen',left:g?`<button type="button" class="btn danger" data-action="delete-goal" data-id="${esc(g.id)}">Löschen</button>`:''}))}
function challengeSheet(id=''){const c=id?state.challenges.find(x=>x.id===id):null;openSheet(sheetWrap(c?'Challenge bearbeiten':'Eigene Challenge','CHALLENGE',`<label>Name<input name="name" required maxlength="70" value="${esc(c?.name||'')}" placeholder="z. B. Urlaubskasse 600 €"></label><label>Zielbetrag<input name="target" type="number" min="1" step="0.01" inputmode="decimal" required value="${c?.target||''}" placeholder="600"></label><label>Anzahl Schritte<input name="steps" type="number" min="1" max="365" step="1" inputmode="numeric" required value="${c?.steps||12}" placeholder="12"></label><label>Zieldatum<input name="deadline" type="date" value="${esc(c?.deadline||'')}"></label>`,{form:'challenge',id:c?.id||'',label:c?'Speichern':'Challenge erstellen',left:c?`<button type="button" class="btn danger" data-action="delete-challenge" data-id="${esc(c.id)}">Löschen</button>`:''}))}
function moneySheet(id,dir){const g=state.goals.find(x=>x.id===id);openSheet(sheetWrap(dir==='add'?'Zum Ziel sparen':'Vom Ziel entnehmen',g?.name||'Sparziel',`<label>Betrag<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" required autofocus placeholder="0,00"></label>`,{form:'goal-money',id, label:dir==='add'?'Hinzufügen':'Entnehmen',left:`<input type="hidden" name="dir" value="${dir}">`}))}
function settingsSheet(){openSheet(`<div class="sheet"><div class="handle"></div><header><div><span class="eyebrow">NEST V${VERSION}</span><h2>Einstellungen</h2></div><button class="close" data-action="close">×</button></header><div class="sheet-body"><button class="row" data-action="opening"><div class="row-main"><strong>Startbetrag</strong><small>${euro(state.openingBalance)}</small></div><span>›</span></button><button class="row" data-action="theme"><div class="row-main"><strong>Darstellung</strong><small>${state.settings.theme==='dark'?'Dunkel':'Hell'}</small></div><span>›</span></button></div></div>`)}
app.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-route]');if(!b)return;if(b.dataset.route){route=b.dataset.route;render();return}const a=b.dataset.action;if(a==='primary-add'){if(route==='transactions')txSheet();if(route==='goals')goalSheet();if(route==='challenges')challengeSheet()}else if(a==='add-tx')txSheet();else if(a==='edit-tx')txSheet(b.dataset.id);else if(a==='add-goal')goalSheet();else if(a==='edit-goal')goalSheet(b.dataset.id);else if(a==='add-challenge')challengeSheet();else if(a==='edit-challenge')challengeSheet(b.dataset.id);else if(a==='goal-money')moneySheet(b.dataset.id,b.dataset.dir);else if(a==='challenge-step')mutate(s=>{const c=s.challenges.find(x=>x.id===b.dataset.id);if(c)c.completed=clamp(c.completed+n(b.dataset.dir),0,c.steps)},'Challenge aktualisiert');else if(a==='settings')settingsSheet();else if(a==='close')closeSheet()})
sheet.addEventListener('click',e=>{if(e.target===sheet)closeSheet();const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='close')closeSheet();else if(a==='delete-tx'&&confirm('Buchung löschen?')){mutate(s=>s.transactions=s.transactions.filter(x=>x.id!==b.dataset.id),'Buchung gelöscht');closeSheet()}else if(a==='delete-goal'&&confirm('Sparziel löschen?')){mutate(s=>s.goals=s.goals.filter(x=>x.id!==b.dataset.id),'Sparziel gelöscht');closeSheet()}else if(a==='delete-challenge'&&confirm('Challenge löschen?')){mutate(s=>s.challenges=s.challenges.filter(x=>x.id!==b.dataset.id),'Challenge gelöscht');closeSheet()}else if(a==='theme'){mutate(s=>s.settings.theme=s.settings.theme==='dark'?'light':'dark');closeSheet()}else if(a==='opening'){const v=prompt('Startbetrag in Euro',String(state.openingBalance).replace('.',','));if(v!==null){const amount=Number(String(v).replace(',','.'));if(Number.isFinite(amount)){mutate(s=>s.openingBalance=amount,'Startbetrag gespeichert');closeSheet()}}}})
sheet.addEventListener('submit',e=>{e.preventDefault();const f=e.target.closest('form[data-form]');if(!f)return;const d=new FormData(f),kind=f.dataset.form,id=f.dataset.id;if(kind==='transaction'){const type=String(d.get('type'));const tx=normalizeTransaction({id:id||uid('tx'),type,amount:d.get('amount'),title:d.get('title'),category:d.get('category'),date:d.get('date'),note:d.get('note'),createdAt:id?state.transactions.find(x=>x.id===id)?.createdAt:Date.now()});mutate(s=>{const i=s.transactions.findIndex(x=>x.id===id);if(i>=0)s.transactions[i]=tx;else s.transactions.push(tx)},id?'Buchung gespeichert':'Buchung angelegt')}if(kind==='goal'){const data=normalizeGoal({id:id||uid('goal'),name:d.get('name'),target:d.get('target'),saved:id?state.goals.find(x=>x.id===id)?.saved:0,deadline:d.get('deadline'),createdAt:id?state.goals.find(x=>x.id===id)?.createdAt:Date.now()});mutate(s=>{const i=s.goals.findIndex(x=>x.id===id);if(i>=0)s.goals[i]=data;else s.goals.push(data)},id?'Sparziel gespeichert':'Sparziel erstellt')}if(kind==='goal-money'){const amount=Math.max(0,n(d.get('amount'))),dir=String(d.get('dir'));mutate(s=>{const g=s.goals.find(x=>x.id===id);if(g)g.saved=Math.max(0,g.saved+(dir==='add'?amount:-amount))},dir==='add'?'Sparbetrag hinzugefügt':'Betrag entnommen')}if(kind==='challenge'){const old=id?state.challenges.find(x=>x.id===id):null;const c=createCustomChallenge({name:d.get('name'),target:d.get('target'),steps:d.get('steps'),deadline:d.get('deadline')});if(old){c.id=old.id;c.completed=Math.min(old.completed,c.steps);c.createdAt=old.createdAt}mutate(s=>{const i=s.challenges.findIndex(x=>x.id===id);if(i>=0)s.challenges[i]=c;else s.challenges.push(c)},id?'Challenge gespeichert':'Eigene Challenge erstellt')}closeSheet()})
window.addEventListener('error',e=>{if(root.__SELFMADE_READY__)return;app.innerHTML=`<main class="boot"><div class="brand-mark">!</div><h1>Startfehler</h1><p>${esc(e.message||'NEST konnte nicht starten.')}</p></main>`})
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}))
render()
})(typeof globalThis!=='undefined'?globalThis:this)
