import {mkdir,rm,copyFile,readFile} from 'node:fs/promises'
import {spawnSync} from 'node:child_process'
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true})
const active=['index.html','styles.css','nav.css','settings-v1.3.css','v2.css','v2-nav-center.css','v202.css','challenges-v2.0.2.css','savings-v2.1.css','savings-v2.1-compact.css','shopping-v2.2.css','boot-v2.0.2.js','v202-core-safe.js','shopping-core-v2.2.js','v202-wallet-guard.js','import-v2.0.2.js','challenges-v2.0.2.js','app-v2.0.2.js','savings-v2.1.js','savings-v2.1-compact.js','shopping-v2.2.js','settings-v2.0.2.js','manifest.webmanifest','sw.js','icon.svg']
for(const f of active)await copyFile(f,`dist/${f}`)
for(const f of ['boot-v2.0.2.js','v202-core-safe.js','shopping-core-v2.2.js','v202-wallet-guard.js','import-v2.0.2.js','challenges-v2.0.2.js','app-v2.0.2.js','savings-v2.1.js','savings-v2.1-compact.js','shopping-v2.2.js','settings-v2.0.2.js','sw.js','api/import-transaction.js','api/product-lookup.js']){const r=spawnSync(process.execPath,['--check',f],{encoding:'utf8'});if(r.status!==0)throw new Error(`${f}: ${r.stderr||r.stdout}`)}
for(const test of ['tests.mjs','import-tests.cjs','v2-tests.cjs','v202-tests.cjs','challenges-tests.cjs','savings-v2.1-tests.cjs','shopping-v2.2-tests.cjs']){const r=spawnSync(process.execPath,[test],{encoding:'utf8'});if(r.status!==0)throw new Error(`${test}: ${r.stderr||r.stdout}`);console.log(r.stdout.trim())}
const sources=['index.html','boot-v2.0.2.js','v202-core-safe.js','shopping-core-v2.2.js','v202-wallet-guard.js','import-v2.0.2.js','challenges-v2.0.2.js','app-v2.0.2.js','savings-v2.1.js','savings-v2.1-compact.js','shopping-v2.2.js','settings-v2.0.2.js','manifest.webmanifest','sw.js','vercel.json','api/import-transaction.js','api/product-lookup.js']
const all=(await Promise.all(sources.map(f=>readFile(f,'utf8')))).join('\n')
for(const token of ['2.2.0','selfmade-save-v1','nest-shopping-v2.2','nest-shopping-v2.2-backup','NestShoppingCoreV22','Einkaufsliste','Barcode','Produktdetails','Kalorien','Fett','Zucker','Eiweiß','Open Food Facts','/api/product-lookup','camera=(self)','@zxing/browser@0.2.1','Gespeicherter Wert konnte nicht verifiziert werden','Buchungsprotokoll','savings-v2.1-compact.js'])if(!all.includes(token))throw new Error(`QA fehlt: ${token}`)
for(const forbidden of ['<script src="/app.js','<script src="/v2-ui.js','<script src="/settings-v1.3.js','<script src="/v202-core.js','Storage.prototype.setItem','camera=()'])if(all.includes(forbidden))throw new Error(`Legacy/Risiko aktiv: ${forbidden}`)
for(const token of ['Steiermärkische','George CSV','PSD2','Automatisch verbinden'])if(all.includes(token))throw new Error(`Bank-Rest gefunden: ${token}`)
console.log('NEST V2.2.0: Einkaufsliste, Barcode-Scanner, Produktdaten, Nährwerte, Kamera-Freigabe, Persistenz, Sparen, Wallet und Navigation geprüft.')
