import {mkdir,rm,copyFile,readFile} from 'node:fs/promises'
import {spawnSync} from 'node:child_process'
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true})
const active=['index.html','styles.css','nav.css','settings-v1.3.css','v2.css','v2-nav-center.css','v202.css','challenges-v2.0.2.css','savings-v2.1.css','savings-v2.1-compact.css','boot-v2.0.2.js','v202-core-safe.js','v202-wallet-guard.js','import-v2.0.2.js','challenges-v2.0.2.js','app-v2.0.2.js','savings-v2.1.js','savings-v2.1-compact.js','settings-v2.0.2.js','manifest.webmanifest','sw.js','icon.svg']
for(const f of active)await copyFile(f,`dist/${f}`)
for(const f of ['boot-v2.0.2.js','v202-core-safe.js','v202-wallet-guard.js','import-v2.0.2.js','challenges-v2.0.2.js','app-v2.0.2.js','savings-v2.1.js','savings-v2.1-compact.js','settings-v2.0.2.js','sw.js','api/import-transaction.js']){const r=spawnSync(process.execPath,['--check',f],{encoding:'utf8'});if(r.status!==0)throw new Error(`${f}: ${r.stderr||r.stdout}`)}
for(const test of ['tests.mjs','import-tests.cjs','v2-tests.cjs','v202-tests.cjs','challenges-tests.cjs','savings-v2.1-tests.cjs']){const r=spawnSync(process.execPath,[test],{encoding:'utf8'});if(r.status!==0)throw new Error(`${test}: ${r.stderr||r.stdout}`);console.log(r.stdout.trim())}
const all=(await Promise.all(['index.html','boot-v2.0.2.js','v202-core-safe.js','v202-wallet-guard.js','import-v2.0.2.js','challenges-v2.0.2.js','app-v2.0.2.js','savings-v2.1.js','savings-v2.1-compact.js','settings-v2.0.2.js','manifest.webmanifest','sw.js','api/import-transaction.js'].map(f=>readFile(f,'utf8')))).join('\n')
for(const token of ['2.1.0','selfmade-save-v1','selfmade-save-v1-backup-v202','nest-audit-v2','NestV202','Gespeicherter Wert konnte nicht verifiziert werden','Neue Buchung','<svg','Wallet-Import','Buchungsprotokoll','Startfehler','v202-core-safe.js','Vorlage hinzufügen','cleanupOldDefaults','52-Wochen-Challenge','Alles, wofür du sparst.','Sparziele und Challenges jetzt gemeinsam','savings-v2.1.js','savings-v2.1-compact.js','Was möchtest du hinzufügen?','data-v21-quick'])if(!all.includes(token))throw new Error(`QA fehlt: ${token}`)
for(const forbidden of ['<script src="/app.js','<script src="/v2-ui.js','<script src="/settings-v1.3.js','<script src="/v202-core.js','Storage.prototype.setItem'])if(all.includes(forbidden))throw new Error(`Legacy-Runtime aktiv: ${forbidden}`)
for(const token of ['Steiermärkische','George CSV','PSD2','Automatisch verbinden'])if(all.includes(token))throw new Error(`Bank-Rest gefunden: ${token}`)
console.log('NEST V2.1.0: kompakter Sparbereich mit zentralem Plus, gemeinsamer Sparbereich, Persistenz, Challenges, Wallet, Navigation und Audit geprüft.')
