import {mkdir,rm,copyFile,readFile} from 'node:fs/promises'
import {spawnSync} from 'node:child_process'
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true})
const active=['index.html','v3.css','v3-shopping.css','v301-shopping.css','tasks-v3.1.css','v3-dialogs.css','v32-bookings.css','v44-performance.css','boot-v2.0.2.js','v202-core-safe.js','shopping-core-v3.js','tasks-core-v3.1-fixed.js','tasks-v3.1.js','v202-wallet-guard.js','import-v2.0.2.js','native-v44.js','app-v3.js','settings-v3.js','v301-shopping.js','v32-bookings.js','v322-nav.js','manifest.webmanifest','sw.js','icon.svg','icon-maskable.svg']
for(const f of active)await copyFile(f,`dist/${f}`)
for(const f of ['boot-v2.0.2.js','v202-core-safe.js','shopping-core-v3.js','tasks-core-v3.1-fixed.js','tasks-v3.1.js','v202-wallet-guard.js','import-v2.0.2.js','native-v44.js','app-v3.js','settings-v3.js','v301-shopping.js','v32-bookings.js','v322-nav.js','sw.js','local-server.mjs','api/import-transaction.js','api/product-lookup.js']){const r=spawnSync(process.execPath,['--check',f],{encoding:'utf8'});if(r.status!==0)throw new Error(`${f}: ${r.stderr||r.stdout}`)}
for(const test of ['tests.mjs','import-tests.cjs','v2-tests.cjs','v202-tests.cjs','v3-tests.cjs','v301-v31-tests.cjs','tasks-v3.1-fixed-tests.cjs','v32-tests.cjs','v321-recurring-tests.cjs','v322-nav-tests.cjs','v44-performance-tests.cjs','ios-sideload-tests.cjs']){const r=spawnSync(process.execPath,[test],{encoding:'utf8'});if(r.status!==0)throw new Error(`${test}: ${r.stderr||r.stdout}`);console.log(r.stdout.trim())}
const sources=['index.html','v3.css','v3-shopping.css','v301-shopping.css','tasks-v3.1.css','v3-dialogs.css','v32-bookings.css','v44-performance.css','boot-v2.0.2.js','v202-core-safe.js','shopping-core-v3.js','tasks-core-v3.1-fixed.js','tasks-v3.1.js','v202-wallet-guard.js','import-v2.0.2.js','native-v44.js','app-v3.js','settings-v3.js','v301-shopping.js','v32-bookings.js','v322-nav.js','manifest.webmanifest','sw.js','vercel.json','api/import-transaction.js','api/product-lookup.js','local-server.mjs','capacitor.config.json']
const all=(await Promise.all(sources.map(f=>readFile(f,'utf8')))).join('\n')
for(const token of ['4.4.0','v44-performance','content-visibility:auto','TX_BATCH=120','stateCacheRaw','Performance-Kern','capacitor:','at.nest.selfmade','native-v44','3.2.1','v32-bookings','Lebensmittel','Mobilität','Gehalt','Rückzahlung','Vierteljährlich','Alle 6 Monate','Jährlich','nest-recurring-v3.2.1','Nächste Buchung','selfmade-save-v1','nest-shopping-v2.2','nest-tasks-v3.1','nest-tasks-v3.1-backup','NestTasksCoreV31','Aufgaben','Heute','Demnächst','Erledigt','Wöchentlich','Monatlich','reminderMinutes','moveTomorrow','v31-reordering','v31-swipe-action','Rückgängig','Verknüpfen mit','Aufgabenspeicher','tasks:','v3-plus','Barcode scannen','Kalorien','Fett','camera=(self)','@zxing/browser@0.2.1','Vollständiges Backup'])if(!all.includes(token))throw new Error(`QA fehlt: ${token}`)
const index=await readFile('index.html','utf8')
if(index.indexOf('/tasks-v3.1.js')>index.indexOf('/app-v3.js'))throw new Error('Aufgaben-Click-Layer muss vor app-v3 geladen werden')
if(index.indexOf('/native-v44.js')>index.indexOf('/app-v3.js'))throw new Error('Native Bridge muss vor app-v3 geladen werden')
if(index.indexOf('/v32-bookings.js')<index.indexOf('/app-v3.js'))throw new Error('Buchungs-UI muss nach app-v3 geladen werden')
if(index.indexOf('/v322-nav.js')<index.indexOf('/v32-bookings.js'))throw new Error('Navigation muss nach Buchungs-UI geladen werden')
if(!index.includes('/v44-performance.css?v=4.4.0-r20'))throw new Error('V4.4 Performance CSS fehlt')
if(!index.includes('/native-v44.js?v=4.4.0-r20'))throw new Error('Native iOS Bridge fehlt')
if(index.includes('/tasks-core-v3.1.js'))throw new Error('Veralteter Aufgaben-Core noch aktiv')
for(const forbidden of ['app-v2.0.2.js','shopping-v2.2.js','savings-v2.1.js','savings-v2.1-compact.js','challenges-v2.0.2.js','release-v2.2.js','settings-v2.2.js','v2-ui.js','settings-v1.3.js'])if(index.includes(forbidden))throw new Error(`Alte UI noch aktiv: ${forbidden}`)
for(const forbidden of ['Storage.prototype.setItem','camera=()'])if(all.includes(forbidden))throw new Error(`Risiko aktiv: ${forbidden}`)
for(const token of ['Steiermärkische','George CSV','PSD2','Automatisch verbinden'])if(all.includes(token))throw new Error(`Bank-Rest gefunden: ${token}`)
console.log('NEST V4.4.0: Performance-Kern, Native-iOS-Bridge, Sideloadly-Build, Read-Caches, Recovery, gestaffelte Buchungen, Navigation, Kategorie-Icons, wiederkehrende Buchungen, Aufgaben, Einkauf, Scanner, Backup und Persistenz geprüft.')
