(function(root,factory){
'use strict'
var api=factory(root&&root.NestV202,root&&root.NestChallengesV202)
if(typeof module!=='undefined'&&module.exports)module.exports=api
if(root)root.NestSavingsV21=api
})(typeof globalThis!=='undefined'?globalThis:this,function(Core,Challenges){
'use strict'
var RELEASE='2.1.0'
var scheduled=false
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d||0)}
function clamp(v,min,max){return Math.min(max,Math.max(min,v))}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function euro(v){try{return new Intl.NumberFormat('de-AT',{style:'currency',currency:'EUR'}).format(n(v,0))}catch(e){return n(v,0).toFixed(2)+' €'}}
function fmtDate(value){if(!value)return'';try{return new Intl.DateTimeFormat('de-AT').format(new Date(String(value).slice(0,10)+'T12:00:00'))}catch(e){return String(value)}}
function setText(el,value){if(el&&String(el.textContent)!==String(value))el.textContent=value}
function goalProgress(g){var target=Math.max(0,n(g&&g.target,0)),saved=Math.max(0,n(g&&g.saved,0)),pct=target?Math.round(clamp(saved/target,0,1)*100):0;return{target:target,saved:saved,remaining:Math.max(0,target-saved),percent:pct}}
function challengeProgress(c){if(Challenges&&Challenges.progressFor)return Challenges.progressFor(c);var steps=Math.max(1,n(c&&c.steps,1)),completed=Math.max(0,Math.min(steps,n(c&&c.completed,0))),target=Math.max(0,n(c&&c.target,0)),saved=target*(completed/steps);return{target:target,saved:saved,remaining:Math.max(0,target-saved),percent:Math.round(completed/steps*100),completed:completed,steps:steps,next:completed<steps?target/steps:0,template:null}}
function totals(state){state=state||{goals:[],challenges:[]};var goalSaved=0,goalTarget=0,challengeSaved=0,challengeTarget=0,i,p;for(i=0;i<(state.goals||[]).length;i++){p=goalProgress(state.goals[i]);goalSaved+=p.saved;goalTarget+=p.target}for(i=0;i<(state.challenges||[]).length;i++){p=challengeProgress(state.challenges[i]);challengeSaved+=p.saved;challengeTarget+=p.target}return{items:(state.goals||[]).length+(state.challenges||[]).length,goalCount:(state.goals||[]).length,challengeCount:(state.challenges||[]).length,progressSaved:goalSaved+challengeSaved,target:goalTarget+challengeTarget,goalSaved:goalSaved,challengeSaved:challengeSaved}}
function goalCard(g){var p=goalProgress(g);return '<article class="v21-save-card goal-card"><div class="v21-card-head"><div><span class="v21-kind goal">Sparziel</span><h3>'+esc(g.name)+'</h3>'+(g.deadline?'<p>Bis '+esc(fmtDate(g.deadline))+'</p>':'<p>Ohne Zieldatum</p>')+'</div><strong>'+p.percent+'%</strong></div><div class="v21-money"><div><small>Gespart</small><b>'+esc(euro(p.saved))+'</b></div><div><small>Noch offen</small><b>'+esc(euro(p.remaining))+'</b></div></div><div class="v21-progress"><i style="width:'+p.percent+'%"></i></div><div class="v21-card-foot"><span>'+esc(euro(p.target))+' Ziel</span><div><button type="button" class="primary" data-action="goal-money" data-id="'+esc(g.id)+'" data-dir="add">+ Sparen</button><button type="button" data-action="goal-money" data-id="'+esc(g.id)+'" data-dir="remove">Entnehmen</button><button type="button" data-action="edit-goal" data-id="'+esc(g.id)+'">Bearbeiten</button></div></div></article>'}
function challengeCard(c){var p=challengeProgress(c),template=p.template,label=template?'Vorlage':'Challenge',done=p.completed>=p.steps;return '<article class="v21-save-card challenge-card"><div class="v21-card-head"><div><span class="v21-kind challenge">'+esc(label)+'</span><h3>'+esc(c.name)+'</h3><p>'+p.completed+' von '+p.steps+' Schritten</p></div><strong>'+p.percent+'%</strong></div><div class="v21-money"><div><small>Fortschritt</small><b>'+esc(euro(p.saved))+'</b></div><div><small>Noch offen</small><b>'+esc(euro(p.remaining))+'</b></div></div><div class="v21-progress"><i style="width:'+p.percent+'%"></i></div><div class="v21-card-foot"><span>'+(done?'Abgeschlossen':'Nächster Schritt '+esc(euro(p.next)))+'</span><div><button type="button" class="primary" data-action="challenge-step" data-id="'+esc(c.id)+'" data-dir="1" '+(done?'disabled':'')+'>'+(done?'Fertig':'Schritt +')+'</button><button type="button" data-action="challenge-step" data-id="'+esc(c.id)+'" data-dir="-1" '+(p.completed<=0?'disabled':'')+'>Zurück</button><button type="button" data-action="edit-challenge" data-id="'+esc(c.id)+'">Bearbeiten</button><button type="button" class="danger" data-c203-action="delete" data-id="'+esc(c.id)+'">Entfernen</button></div></div></article>'}
function section(title,copy,actionLabel,actionAttr,cards,empty){return '<section class="v21-section"><div class="v21-section-head"><div><span>SPAREN</span><h2>'+esc(title)+'</h2><p>'+esc(copy)+'</p></div><button type="button" class="v21-section-action" '+actionAttr+'>'+esc(actionLabel)+'</button></div>'+(cards?'<div class="v21-grid">'+cards+'</div>':'<div class="v21-empty">'+empty+'</div>')+'</section>'}
function pageMarkup(){var state=Core.loadState(),t=totals(state),goals='',challenges='',i;for(i=0;i<state.goals.length;i++)goals+=goalCard(state.goals[i]);for(i=0;i<state.challenges.length;i++)challenges+=challengeCard(state.challenges[i]);var hero='<section class="v21-hero"><div><span>NEST SPAREN · V'+RELEASE+'</span><h2>Alles, wofür du sparst.</h2><p>Sparziele und Challenges jetzt gemeinsam an einem Ort.</p></div><div class="v21-hero-actions"><button type="button" class="primary" data-action="add-goal">+ Sparziel</button><button type="button" data-c203-action="open-templates">Challenge-Vorlage</button></div></section>';var stats='<section class="v21-stats"><div><small>Aktiv</small><b>'+t.items+'</b><span>'+t.goalCount+' Ziele · '+t.challengeCount+' Challenges</span></div><div><small>Fortschritt</small><b>'+esc(euro(t.progressSaved))+'</b><span>über Ziele & Challenges</span></div><div><small>Zielsumme</small><b>'+esc(euro(t.target))+'</b><span>insgesamt geplant</span></div></section>';var goalEmpty='<h3>Noch kein Sparziel</h3><p>Lege ein konkretes Ziel wie Urlaub, Notgroschen oder neues Gerät an.</p><button type="button" class="primary" data-action="add-goal">Erstes Sparziel erstellen</button>';var challengeEmpty='<h3>Noch keine Challenge</h3><p>Wähle eine Vorlage oder erstelle deine eigene Spar-Challenge.</p><div><button type="button" class="primary" data-c203-action="open-templates">Vorlage auswählen</button><button type="button" data-action="add-challenge">Eigene Challenge</button></div>';return '<div class="v21-savings">'+hero+stats+section('Sparziele','Konkrete Beträge mit frei wählbarem Ziel und Datum.','Neues Sparziel','data-action="add-goal"',goals,goalEmpty)+section('Challenges','Motivierendes Sparen in einzelnen Schritten.','Challenge hinzufügen','data-c203-action="open-templates"',challenges,challengeEmpty)+'</div>'}
function savingsIcon(){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M5 9.5A7 7 0 0 1 18.5 12c0 3.9-3.1 7-7 7H7l-2 2v-4.5A7 7 0 0 1 5 9.5Z"/><path d="M9 8.5h5"/><path d="M12 6v5"/><circle cx="16.5" cy="11" r=".7" fill="currentColor" stroke="none"/></svg>'}
function normalizePrefs(){if(!Core)return;try{var p=Core.loadPrefs();if(p.startRoute==='challenges')p.startRoute='goals';Core.savePrefs(p)}catch(e){}}
function enhanceSettings(){var dialog=document.getElementById('settings202');if(dialog){var version=dialog.querySelector('.s13-head span'),about=dialog.querySelector('.s13-about b');setText(version,'NEST · VERSION '+RELEASE);setText(about,'NEST '+RELEASE)}var select=document.querySelector('#settings202 select[name="startRoute"]');if(!select)return;var goals=select.querySelector('option[value="goals"]'),challenges=select.querySelector('option[value="challenges"]');if(goals)setText(goals,'Sparen');if(challenges)challenges.remove();if(select.value==='challenges')select.value='goals'}
function enhance(){scheduled=false;if(!Core||typeof document==='undefined')return;var app=document.getElementById('app');if(!app)return;var shell=app.querySelector('.shell'),header=shell&&shell.querySelector('header.top'),h1=header&&header.querySelector('h1'),nav=app.querySelector('.tabs');if(!shell||!h1||!nav)return;var eyebrow=header.querySelector('.eyebrow'),foot=nav.querySelector('.v2-nav-foot b');if(eyebrow){var nextEyebrow=String(eyebrow.textContent||'').replace(/NEST\s+2\.0\.2/i,'NEST '+RELEASE);setText(eyebrow,nextEyebrow)}setText(foot,'v'+RELEASE);var challengeNav=nav.querySelector('[data-route="challenges"]'),goalNav=nav.querySelector('[data-route="goals"]');if(challengeNav)challengeNav.remove();if(goalNav){setText(goalNav.querySelector('span'),'Sparen');var icon=goalNav.querySelector('.v2-nav-icon');if(icon&&icon.getAttribute('data-v21-icon')!=='1'){icon.innerHTML=savingsIcon();icon.setAttribute('data-v21-icon','1')}}nav.classList.add('v21-nav');var title=String(h1.textContent||'').trim();if(title==='Challenges'){var goal=nav.querySelector('[data-route="goals"]');if(goal){goal.click();return}}if(title!=='Sparziele'&&title!=='Sparen'){enhanceSettings();return}setText(h1,'Sparen');if(!shell.querySelector('.v21-savings')){var children=Array.prototype.slice.call(shell.children,1);for(var i=0;i<children.length;i++)children[i].remove();shell.insertAdjacentHTML('beforeend',pageMarkup())}enhanceSettings()}
function schedule(){if(scheduled)return;scheduled=true;if(typeof requestAnimationFrame==='function')requestAnimationFrame(enhance);else setTimeout(enhance,0)}
function bind(){normalizePrefs();var app=document.getElementById('app');if(app)new MutationObserver(schedule).observe(app,{childList:true,subtree:true});new MutationObserver(function(){enhanceSettings()}).observe(document.body,{childList:true,subtree:true});schedule()}
var API={RELEASE:RELEASE,goalProgress:goalProgress,challengeProgress:challengeProgress,totals:totals,pageMarkup:pageMarkup}
if(typeof document!=='undefined'&&Core)bind()
return API
})