(function(root){
'use strict'
var Core=root.NestShoppingCoreV22,store=Core&&Core.store
if(!Core||!store)return
var RELEASE=Core.RELEASE,shoppingActive=false,scheduled=false,scanner={stream:null,controls:null,timer:null,busy:false}
var app=document.getElementById('app'),toast=document.getElementById('toast')
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function show(msg,error){if(!toast)return;toast.textContent=msg;toast.classList.toggle('bad',!!error);toast.classList.add('show');clearTimeout(show.t);show.t=setTimeout(function(){toast.classList.remove('show','bad')},2600)}
function icon(type){var map={shopping:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M4 5h2l1.5 9h9.8l1.7-6H7"/><circle cx="10" cy="19" r="1.4"/><circle cx="17" cy="19" r="1.4"/></svg>',scan:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M4 8V5a1 1 0 0 1 1-1h3M16 4h3a1 1 0 0 1 1 1v3M20 16v3a1 1 0 0 1-1 1h-3M8 20H5a1 1 0 0 1-1-1v-3"/><path d="M7 9v6M10 8v8M13 9v6M16 8v8"/></svg>',plus:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.1" stroke-linecap="round"><path d="M12 5v14M5 12h14"/></svg>',info:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7.5h.01"/></svg>'};return map[type]||''}
function formatNutri(v,unit){return Number.isFinite(Number(v))?String(Math.round(Number(v)*10)/10).replace('.',',')+' '+unit:'–'}
function navButton(){return '<button type="button" data-v22-shopping="open"><b class="v2-nav-icon" aria-hidden="true">'+icon('shopping')+'</b><span>Einkauf</span></button>'}
function enhanceNav(){if(!app)return;var nav=app.querySelector('.tabs');if(!nav)return;nav.classList.add('v22-nav');var button=nav.querySelector('[data-v22-shopping]');if(!button){var goal=nav.querySelector('[data-route="goals"]');if(goal)goal.insertAdjacentHTML('beforebegin',navButton());else nav.insertAdjacentHTML('beforeend',navButton());button=nav.querySelector('[data-v22-shopping]')}if(shoppingActive){var actives=nav.querySelectorAll('button.active');for(var i=0;i<actives.length;i++)actives[i].classList.remove('active');if(button)button.classList.add('active')}}
function stats(state){var open=0,done=0,scanned=0;for(var i=0;i<state.items.length;i++){if(state.items[i].checked)done++;else open++;if(state.items[i].product)scanned++}return{open:open,done:done,scanned:scanned,total:state.items.length}}
function itemRow(it){var meta=[],product=it.product;if(product&&product.brand)meta.push(product.brand);if(product&&product.quantity)meta.push(product.quantity);if(!product&&it.barcode)meta.push('EAN '+it.barcode);var image=product&&product.image?'<img src="'+esc(product.image)+'" alt="" loading="lazy" referrerpolicy="no-referrer">':'<span class="v22-item-placeholder">'+(it.name?esc(it.name.charAt(0).toUpperCase()):'•')+'</span>';return '<article class="v22-item '+(it.checked?'done':'')+'" data-id="'+esc(it.id)+'"><button class="v22-check" type="button" data-v22-action="toggle" data-id="'+esc(it.id)+'" aria-label="'+(it.checked?'Als offen markieren':'Als erledigt markieren')+'"><span>✓</span></button><div class="v22-item-image">'+image+'</div><button type="button" class="v22-item-main" data-v22-action="details" data-id="'+esc(it.id)+'"><b>'+esc(it.name)+'</b><small>'+esc(meta.join(' · ')||'Manuell hinzugefügt')+'</small></button><div class="v22-qty"><button type="button" data-v22-action="qty" data-dir="-1" data-id="'+esc(it.id)+'">−</button><b>'+it.count+'</b><button type="button" data-v22-action="qty" data-dir="1" data-id="'+esc(it.id)+'">+</button></div></article>'}
function pageMarkup(){var state=store.load(),s=stats(state),open=[],done=[];for(var i=0;i<state.items.length;i++)(state.items[i].checked?done:open).push(state.items[i]);var openHtml=open.map(itemRow).join(''),doneHtml=done.map(itemRow).join('');return '<div class="v22-shopping"><section class="v22-shop-hero"><div><span>NEST EINKAUF · V'+RELEASE+'</span><h2>Einkaufsliste</h2><p>Produkte schnell notieren oder Barcode scannen und Nährwerte direkt ansehen.</p></div><button type="button" class="v22-scan-main" data-v22-action="scan">'+icon('scan')+'<span>Scannen</span></button></section><section class="v22-shop-stats"><div><small>Offen</small><b>'+s.open+'</b></div><div><small>Erledigt</small><b>'+s.done+'</b></div><div><small>Mit Produktdaten</small><b>'+s.scanned+'</b></div></section><section class="v22-quick"><div class="v22-quick-input"><span>'+icon('plus')+'</span><input id="v22QuickName" type="text" maxlength="120" autocomplete="off" placeholder="Produkt hinzufügen …"><button type="button" data-v22-action="quick-add">Hinzufügen</button></div><button type="button" class="v22-scan-icon" data-v22-action="scan" aria-label="Barcode scannen">'+icon('scan')+'</button></section><section class="v22-list-card"><header><div><span>EINKAUFSLISTE</span><h3>Noch zu kaufen</h3></div><b>'+s.open+'</b></header><div class="v22-list">'+(openHtml||'<div class="v22-empty"><div>'+icon('shopping')+'</div><span><b>Deine Liste ist leer</b><small>Füge ein Produkt hinzu oder scanne den Barcode auf der Verpackung.</small></span></div>')+'</div></section>'+(done.length?'<section class="v22-list-card v22-completed"><header><div><span>ERLEDIGT</span><h3>Im Wagen</h3></div><button type="button" data-v22-action="clear-done">Erledigte löschen</button></header><div class="v22-list">'+doneHtml+'</div></section>':'')+'<p class="v22-source-note">Produkt- und Nährwertdaten werden beim Scan aus Open Food Facts geladen. Fehlende Angaben werden als „–“ angezeigt.</p></div>'}
function renderShopping(){if(!shoppingActive||!app)return;enhanceNav();var shell=app.querySelector('.shell'),header=shell&&shell.querySelector('header.top');if(!shell||!header)return;var h1=header.querySelector('h1'),eyebrow=header.querySelector('.eyebrow');if(h1)h1.textContent='Einkauf';if(eyebrow)eyebrow.textContent=String(eyebrow.textContent||'').replace(/NEST\s+[0-9.]+/i,'NEST '+RELEASE);var children=Array.prototype.slice.call(shell.children,1);for(var i=0;i<children.length;i++)children[i].remove();shell.insertAdjacentHTML('beforeend',pageMarkup());enhanceNav();document.documentElement.dataset.nestRelease=RELEASE}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(function(){scheduled=false;enhanceNav();if(shoppingActive&&!document.querySelector('.v22-shopping'))renderShopping()})}
function ensureDialog(id,cls,label){var d=document.getElementById(id);if(d)return d;d=document.createElement('dialog');d.id=id;d.className=cls;d.setAttribute('aria-label',label);document.body.appendChild(d);d.addEventListener('click',function(e){if(e.target===d)d.close()});return d}
function stopScanner(){if(scanner.timer){clearTimeout(scanner.timer);scanner.timer=null}if(scanner.controls&&scanner.controls.stop)try{scanner.controls.stop()}catch(e){}scanner.controls=null;if(scanner.stream){scanner.stream.getTracks().forEach(function(t){t.stop()});scanner.stream=null}scanner.busy=false}
function closeScanner(){stopScanner();var d=document.getElementById('v22Scanner');if(d&&d.open)d.close()}
function scannerMarkup(){return '<section class="v22-scan-sheet"><header><div><span>BARCODE</span><h2>Produkt scannen</h2><p>Halte den EAN-/UPC-Code gut beleuchtet in den Rahmen.</p></div><button type="button" data-v22-action="close-scan" aria-label="Schließen">×</button></header><div class="v22-camera"><video id="v22Video" playsinline muted></video><div class="v22-scan-frame"><i></i><i></i><i></i><i></i></div><div id="v22ScanStatus">Kamera wird gestartet …</div></div><div class="v22-manual-code"><span>Oder Barcode eingeben</span><div><input id="v22BarcodeInput" inputmode="numeric" autocomplete="off" maxlength="18" placeholder="z. B. 3017624010701"><button type="button" data-v22-action="lookup-code">Suchen</button></div></div></section>'}
async function loadZXing(){if(root.ZXingBrowser)return root.ZXingBrowser;var old=document.getElementById('nestZxingV22');if(old){return new Promise(function(resolve,reject){old.addEventListener('load',function(){resolve(root.ZXingBrowser)},{once:true});old.addEventListener('error',reject,{once:true})})}return new Promise(function(resolve,reject){var s=document.createElement('script');s.id='nestZxingV22';s.src='https://unpkg.com/@zxing/browser@0.2.1/umd/zxing-browser.min.js';s.async=true;s.crossOrigin='anonymous';s.onload=function(){root.ZXingBrowser?resolve(root.ZXingBrowser):reject(new Error('Scanner-Bibliothek nicht verfügbar'))};s.onerror=function(){reject(new Error('Scanner-Bibliothek konnte nicht geladen werden'))};document.head.appendChild(s)})}
async function startNative(video,status){if(!('BarcodeDetector' in root))return false;try{var formats=await root.BarcodeDetector.getSupportedFormats();var wanted=['ean_13','ean_8','upc_a','upc_e'].filter(function(x){return formats.indexOf(x)>=0});if(!wanted.length)return false;var detector=new root.BarcodeDetector({formats:wanted});scanner.stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}});video.srcObject=scanner.stream;await video.play();status.textContent='Barcode in den Rahmen halten';var loop=async function(){if(!scanner.stream||scanner.busy)return;try{var codes=await detector.detect(video);if(codes&&codes[0]&&codes[0].rawValue){scanner.busy=true;return handleBarcode(codes[0].rawValue)}}catch(e){}scanner.timer=setTimeout(loop,220)};loop();return true}catch(e){stopScanner();return false}}
async function startZXing(video,status){try{var ZX=await loadZXing();var reader=new ZX.BrowserMultiFormatReader();var controls=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:'environment'}}},video,function(result,error,ctrl){if(result&&!scanner.busy){scanner.busy=true;scanner.controls=ctrl||scanner.controls;handleBarcode(result.getText?result.getText():String(result.text||result))}});scanner.controls=controls;status.textContent='Barcode in den Rahmen halten';return true}catch(e){console.error('ZXing start failed',e);return false}}
async function openScanner(){if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){show('Kamera ist in diesem Browser nicht verfügbar',true);return}var d=ensureDialog('v22Scanner','v22-scanner-dialog','Barcode scannen');d.innerHTML=scannerMarkup();if(!d.open)d.showModal();var video=d.querySelector('#v22Video'),status=d.querySelector('#v22ScanStatus');stopScanner();var ok=await startNative(video,status);if(!ok)ok=await startZXing(video,status);if(!ok){status.textContent='Kamera-Scan nicht verfügbar – Barcode unten manuell eingeben.';show('Scanner konnte nicht gestartet werden',true)}}
async function lookupProduct(code){var barcode=String(code||'').replace(/\D/g,'');if(!/^\d{7,14}$/.test(barcode))throw new Error('Bitte einen gültigen EAN-/UPC-Barcode eingeben');var response=await fetch('/api/product-lookup?barcode='+encodeURIComponent(barcode),{headers:{Accept:'application/json'}});var data=await response.json().catch(function(){return null});if(!response.ok||!data||!data.ok)throw new Error(data&&data.error==='product_service_timeout'?'Produktdatenbank antwortet zu langsam':'Produktdaten konnten nicht geladen werden');return data}
async function handleBarcode(code){var barcode=String(code||'').replace(/\D/g,'');closeScanner();show('Produkt wird geladen …');try{var data=await lookupProduct(barcode);if(data.found&&data.product)openProduct(data.product,true);else openUnknown(barcode)}catch(e){console.error(e);show(e.message||'Produktdaten konnten nicht geladen werden',true);openUnknown(barcode)}}
function nutritionRows(p){var x=p.nutrition||{};return [['Kalorien',formatNutri(x.energyKcal,'kcal')],['Fett',formatNutri(x.fat,'g')],['Gesättigt',formatNutri(x.saturatedFat,'g')],['Kohlenhydrate',formatNutri(x.carbs,'g')],['Zucker',formatNutri(x.sugars,'g')],['Eiweiß',formatNutri(x.protein,'g')],['Salz',formatNutri(x.salt,'g')],['Ballaststoffe',formatNutri(x.fiber,'g')]].map(function(r){return '<div><small>'+r[0]+'</small><b>'+r[1]+'</b></div>'}).join('')}
function productMarkup(p,canAdd,itemId){var image=p.image?'<img src="'+esc(p.image)+'" alt="" referrerpolicy="no-referrer">':'<div class="v22-product-noimage">'+esc((p.name||'?').charAt(0).toUpperCase())+'</div>';var grade=p.nutriscore?'<span class="v22-nutriscore grade-'+esc(p.nutriscore)+'">Nutri-Score '+esc(p.nutriscore.toUpperCase())+'</span>':'';return '<section class="v22-product-sheet"><header><span>PRODUKTDETAILS</span><button type="button" data-v22-action="close-product" aria-label="Schließen">×</button></header><div class="v22-product-head">'+image+'<div><h2>'+esc(p.name)+'</h2><p>'+esc([p.brand,p.quantity].filter(Boolean).join(' · ')||'Produktdaten')+'</p><small>Barcode '+esc(p.code||'–')+'</small>'+grade+'</div></div><div class="v22-nutrition-title"><div><span>NÄHRWERTE</span><h3>pro 100 g / 100 ml</h3></div></div><div class="v22-nutrition">'+nutritionRows(p)+'</div>'+(p.ingredients?'<div class="v22-product-copy"><b>Zutaten</b><p>'+esc(p.ingredients)+'</p></div>':'')+(p.allergens&&p.allergens.length?'<div class="v22-product-copy"><b>Allergene</b><p>'+esc(p.allergens.join(', '))+'</p></div>':'')+'<p class="v22-product-source">Quelle: '+esc(p.source||'Open Food Facts')+'. Angaben können je nach Datenstand des Produkts unvollständig sein.</p><footer>'+(itemId?'<button type="button" class="danger" data-v22-action="remove" data-id="'+esc(itemId)+'">Von Liste entfernen</button>':'')+(canAdd?'<button type="button" class="primary" data-v22-action="add-scanned" data-code="'+esc(p.code)+'">Zur Einkaufsliste</button>':'')+'<button type="button" data-v22-action="close-product">Schließen</button></footer></section>'}
var currentProduct=null
function openProduct(product,canAdd,itemId){currentProduct=Core.normalizeProduct(product);var d=ensureDialog('v22Product','v22-product-dialog','Produktdetails');d.innerHTML=productMarkup(currentProduct,canAdd,itemId);if(!d.open)d.showModal()}
function openUnknown(barcode){var d=ensureDialog('v22Product','v22-product-dialog','Produkt nicht gefunden');d.innerHTML='<section class="v22-product-sheet"><header><span>BARCODE '+esc(barcode)+'</span><button type="button" data-v22-action="close-product">×</button></header><div class="v22-unknown"><div>'+icon('info')+'</div><h2>Produkt nicht gefunden</h2><p>Für diesen Barcode sind aktuell keine Produktdaten verfügbar. Du kannst das Produkt trotzdem manuell zur Liste hinzufügen.</p><label>Produktname<input id="v22UnknownName" maxlength="120" placeholder="Produktname"></label></div><footer><button type="button" data-v22-action="close-product">Abbrechen</button><button type="button" class="primary" data-v22-action="add-unknown" data-code="'+esc(barcode)+'">Hinzufügen</button></footer></section>';if(!d.open)d.showModal()}
function details(id){var state=store.load(),it=state.items.find(function(x){return x.id===id});if(!it)return;if(it.product)openProduct(it.product,false,it.id);else{var d=ensureDialog('v22Product','v22-product-dialog','Listeneintrag');d.innerHTML='<section class="v22-product-sheet"><header><span>LISTENEINTRAG</span><button type="button" data-v22-action="close-product">×</button></header><div class="v22-unknown"><h2>'+esc(it.name)+'</h2><p>Dieser Eintrag wurde manuell erstellt und enthält keine hinterlegten Produktdaten.</p></div><footer><button type="button" class="danger" data-v22-action="remove" data-id="'+esc(it.id)+'">Von Liste entfernen</button><button type="button" data-v22-action="close-product">Schließen</button></footer></section>';if(!d.open)d.showModal()}}
function closeProduct(){var d=document.getElementById('v22Product');if(d&&d.open)d.close();currentProduct=null}
function saveAction(fn,message){try{fn();renderShopping();if(message)show(message)}catch(e){console.error(e);show(e.message||'Änderung konnte nicht gespeichert werden',true)}}
function quickAdd(){var input=document.getElementById('v22QuickName'),name=input&&input.value.trim();if(!name){input&&input.focus();return}saveAction(function(){store.addManual(name,1)},'Produkt hinzugefügt')}
function enhanceSettings(){var d=document.getElementById('settings202');if(!d)return;var version=d.querySelector('.s13-head span'),about=d.querySelector('.s13-about b');if(version)version.textContent='NEST · VERSION '+RELEASE;if(about)about.textContent='NEST '+RELEASE}
document.addEventListener('click',function(e){var shop=e.target.closest&&e.target.closest('[data-v22-shopping]');if(shop){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();shoppingActive=true;closeScanner();closeProduct();renderShopping();return}var base=e.target.closest&&e.target.closest('[data-route]');if(base&&shoppingActive){shoppingActive=false;closeScanner();closeProduct();return}var b=e.target.closest&&e.target.closest('[data-v22-action]');if(!b)return;var action=b.getAttribute('data-v22-action');e.preventDefault();e.stopPropagation();
if(action==='scan')openScanner();else if(action==='close-scan')closeScanner();else if(action==='lookup-code'){var inp=document.getElementById('v22BarcodeInput');handleBarcode(inp&&inp.value)}else if(action==='quick-add')quickAdd();else if(action==='toggle')saveAction(function(){store.toggle(b.getAttribute('data-id'))});else if(action==='qty'){var id=b.getAttribute('data-id'),dir=Number(b.getAttribute('data-dir')),it=store.load().items.find(function(x){return x.id===id});if(it)saveAction(function(){store.setCount(id,it.count+dir)})}else if(action==='clear-done'){if(confirm('Alle erledigten Produkte von der Liste entfernen?'))saveAction(function(){store.clearChecked()},'Erledigte Produkte entfernt')}else if(action==='details')details(b.getAttribute('data-id'));else if(action==='close-product')closeProduct();else if(action==='add-scanned'){if(currentProduct)saveAction(function(){store.addProduct(currentProduct,1)},'Produkt zur Liste hinzugefügt');closeProduct()}else if(action==='add-unknown'){var nameInput=document.getElementById('v22UnknownName'),name=nameInput&&nameInput.value.trim(),code=b.getAttribute('data-code');if(!name){nameInput&&nameInput.focus();return}saveAction(function(){var r=store.addManual(name,1),s=r.state,item=s.items.find(function(x){return x.id===r.item.id});item.barcode=String(code||'');store.save(s)},'Produkt hinzugefügt');closeProduct()}else if(action==='remove'){var rid=b.getAttribute('data-id');if(confirm('Produkt wirklich von der Einkaufsliste entfernen?')){saveAction(function(){store.remove(rid)},'Produkt entfernt');closeProduct()}}
},true)
document.addEventListener('keydown',function(e){if(e.key==='Enter'&&document.activeElement&&document.activeElement.id==='v22QuickName'){e.preventDefault();quickAdd()}})
var observer=new MutationObserver(function(){schedule();enhanceSettings()});if(app)observer.observe(app,{childList:true,subtree:true});observer.observe(document.body,{childList:true});
root.addEventListener('storage',function(e){if((e.key===Core.STORE_KEY||e.key===Core.BACKUP_KEY)&&shoppingActive)renderShopping()})
root.addEventListener('pagehide',stopScanner);root.addEventListener('beforeunload',stopScanner)
schedule();enhanceSettings()
root.NestShoppingV22={RELEASE:RELEASE,open:function(){shoppingActive=true;renderShopping()},lookupProduct:lookupProduct,openScanner:openScanner,store:store,exportData:function(){return store.exportData()},importData:function(x){return store.importData(x)},reset:function(){return store.reset()},status:function(){return store.status()}}
})(typeof globalThis!=='undefined'?globalThis:this)
