const assert=require('node:assert/strict')
const T=require('./tasks-core-v3.1.js')
class MemoryStorage{constructor(){this.map=new Map();this.fail=false}getItem(k){return this.map.has(k)?this.map.get(k):null}setItem(k,v){if(this.fail)throw new Error('write blocked');this.map.set(k,String(v))}removeItem(k){this.map.delete(k)}}
const storage=new MemoryStorage(),store=T.createStore(storage)
assert.equal(T.RELEASE,'3.1.0')
assert.equal(T.addDays('2026-08-09',1),'2026-08-10')
assert.equal(T.nextDate('2026-08-09','weekly'),'2026-08-16')
assert.equal(T.nextDate('2026-01-31','monthly'),'2026-02-28')
let state=store.load();assert.deepEqual(state.tasks,[])
let r=store.add({title:'Müll rausbringen',date:'2026-08-09',time:'19:00',priority:'high',reminderMinutes:-15,repeat:'weekly',linkType:'none'})
assert.equal(r.task.title,'Müll rausbringen');assert.equal(r.task.priority,'high');assert.equal(r.task.repeat,'weekly')
const id=r.task.id
assert.equal(T.bucket(r.task,'2026-08-09'),'today')
assert.equal(T.bucket({...r.task,date:'2026-08-10'},'2026-08-09'),'upcoming')
let due=T.reminderAt(r.task);assert.equal(due,new Date(2026,7,9,18,45,0,0).getTime())
store.toggle(id);state=store.load();assert.equal(state.tasks.find(x=>x.id===id).completed,true)
const next=state.tasks.find(x=>x.occurrenceOf===id);assert.ok(next);assert.equal(next.date,'2026-08-16');assert.equal(next.completed,false)
store.toggle(id);state=store.load();assert.equal(state.tasks.find(x=>x.id===id).completed,false);assert.equal(state.tasks.filter(x=>x.occurrenceOf===id).length,1)
store.moveTomorrow(id,'2026-08-09');assert.equal(store.load().tasks.find(x=>x.id===id).date,'2026-08-10')
store.update(id,{reminderMinutes:0,date:'2026-08-09',time:'10:00',completed:false,remindedAt:0});assert.ok(store.dueReminders(new Date(2026,7,9,10,1).getTime()).some(x=>x.id===id))
store.markReminded(id,new Date(2026,7,9,10,1).getTime());assert.ok(!store.dueReminders(new Date(2026,7,9,10,2).getTime()).some(x=>x.id===id))
const a=store.add({title:'A',date:'2026-08-11'}).task,b=store.add({title:'B',date:'2026-08-11'}).task;store.reorder([b.id,a.id]);state=store.load();assert.ok(state.tasks.find(x=>x.id===b.id).order<state.tasks.find(x=>x.id===a.id).order)
const stable=store.load();storage.setItem(T.STORE_KEY,'{broken');const recovered=store.load();assert.equal(recovered.tasks.length,stable.tasks.length)
storage.fail=true;assert.throws(()=>store.save({...stable,tasks:[]}),/write blocked|verifiziert/);storage.fail=false;assert.equal(store.load().tasks.length,stable.tasks.length)
const exported=store.exportData();store.remove(a.id);store.importData(exported);assert.ok(store.load().tasks.some(x=>x.id===a.id))
store.reset();assert.equal(storage.getItem(T.STORE_KEY),null);assert.equal(storage.getItem(T.BACKUP_KEY),null)
console.log('NEST v3.1 task storage, recurrence, reminders, reorder and recovery tests passed.')
