const assert=require('node:assert/strict')
const Shopping=require('./shopping-core-v3.js')
const Product=require('./api/product-lookup.js')._test
class MemoryStorage{constructor(){this.map=new Map();this.fail=false}getItem(k){return this.map.has(k)?this.map.get(k):null}setItem(k,v){if(this.fail)throw new Error('write blocked');this.map.set(k,String(v))}removeItem(k){this.map.delete(k)}}
const storage=new MemoryStorage(),store=Shopping.createStore(storage)
assert.equal(Shopping.RELEASE,'3.0.0')
assert.equal(Shopping.inferCategory('Bananen',''),'Obst & Gemüse')
assert.equal(Shopping.inferCategory('Vollmilch 3,5%',''),'Milch & Kühlung')
assert.equal(Shopping.inferCategory('Mineralwasser',''),'Getränke')
assert.deepEqual(Shopping.parseEntry('1,5 kg Bananen'),{name:'Bananen',amount:1.5,unit:'kg',detected:true})
let parsed=store.addManual({name:'2 kg Kartoffeln',amount:1,unit:'stk',category:'auto'});assert.equal(parsed.item.name,'Kartoffeln');assert.equal(parsed.item.amount,2);assert.equal(parsed.item.unit,'kg');assert.equal(parsed.item.category,'Obst & Gemüse')
let r=store.addManual({name:'Bananen',amount:1.5,unit:'kg',category:'auto'})
assert.equal(r.item.unit,'kg');assert.equal(r.item.amount,1.5);assert.equal(r.item.category,'Obst & Gemüse')
r=store.addProduct({code:'3017624010701',name:'Nutella',brand:'Ferrero',quantity:'450 g',productQuantity:450,productQuantityUnit:'g',category:'Vorrat',nutrition:{energyKcal:539,fat:30.9,sugars:56.3,protein:6.3}},{amount:1,unit:'pkg'})
assert.equal(r.item.product.nutrition.energyKcal,539);assert.equal(r.item.product.productQuantity,450);assert.equal(r.item.unit,'pkg')
const firstId=r.item.id
r=store.addProduct({code:'3017624010701',name:'Nutella',category:'Vorrat'},{amount:2,unit:'pkg'})
assert.equal(r.merged,true);assert.equal(store.load().items.find(x=>x.id===firstId).amount,3)
store.update(firstId,{amount:500,unit:'g'});assert.equal(store.load().items.find(x=>x.id===firstId).unit,'g')
const stable=store.load();storage.setItem(Shopping.STORE_KEY,'{broken');assert.equal(store.load().items.length,stable.items.length)
storage.fail=true;assert.throws(()=>store.save({...stable,items:[]}),/write blocked|verifiziert/);storage.fail=false;assert.equal(store.load().items.length,stable.items.length)
assert.equal(Product.API_VERSION,'v3.6');assert.equal(Product.API_PATH_VERSION,'v3')
assert.equal(Product.normalizeBarcode('3017 6240 10701'),'3017624010701')
let e=Product.energy({'energy-kj_100g':418.4});assert.equal(e.energyKcal,100);assert.equal(e.energyKj,418.4)
e=Product.energy({'energy-kcal_100g':200});assert.equal(e.energyKcal,200);assert.equal(e.energyKj,836.8)
const mapped=Product.mapProduct({code:'3017624010701',product_name:'Nutella',brands:'Ferrero',quantity:'450 g',product_quantity:'450',product_quantity_unit:'g',categories:'Spreads, Chocolate spreads',nutriments:{'energy-kcal_100g':539,'energy-kj_100g':2255,fat_100g:30.9,'saturated-fat_100g':10.6,carbohydrates_100g:57.5,sugars_100g:56.3,proteins_100g:6.3,salt_100g:.107}},'3017624010701')
assert.equal(mapped.nutrition.energyKcal,539);assert.equal(mapped.nutrition.fat,30.9);assert.equal(mapped.nutrition.protein,6.3);assert.equal(mapped.productQuantity,450);assert.equal(mapped.productQuantityUnit,'g');assert.equal(mapped.nutritionAvailable,true)
assert.ok(Product.FIELDS.includes('product_quantity'));assert.ok(Product.FIELDS.includes('nutriments'))
console.log('NEST v3 shopping, unit/category migration and nutrition regression tests passed.')
