const assert=require('node:assert/strict')
const fs=require('node:fs')
const Swipe=require('./v301-shopping.js')
assert.equal(Swipe.RELEASE,'3.0.1')
assert.equal(Swipe.settleSwipe(-10,82,38),0)
assert.equal(Swipe.settleSwipe(-37,82,38),0)
assert.equal(Swipe.settleSwipe(-38,82,38),-82)
assert.equal(Swipe.settleSwipe(-120,82,38),-82)
assert.equal(Swipe.clamp(-100,-82,0),-82)
assert.equal(Swipe.clamp(10,-82,0),0)
const css=fs.readFileSync('v301-shopping.css','utf8')
assert.match(css,/\.v3-product-img\{display:none!important\}/)
assert.match(css,/\.v3-check\{width:26px;height:26px/)
assert.match(css,/\.v301-swipe-delete/)
const js=fs.readFileSync('v301-shopping.js','utf8')
assert.match(js,/Rückgängig/)
assert.match(js,/pointermove/)
assert.match(js,/touch-action:pan-y|v301-swipe/)
console.log('NEST v3.0.1 compact shopping row, swipe threshold and undo regression tests passed.')
