(function(root,factory){
'use strict'
var api=factory(root)
if(typeof module!=='undefined'&&module.exports)module.exports=api
if(root)root.NestLidlV4=api
})(typeof globalThis!=='undefined'?globalThis:this,function(root){
'use strict'
const RELEASE='4.0.0'
const STORE_KEY='nest-lidl-v4'
const BACKUP_KEY='nest-lidl-v4-backup'
const SOURCE_URL='https://www.lidl.at/c/'
const Shopping=root&&root.NestShoppingCoreV3
const Shop=Shopping&&Shopping.store
const memory={}
const STOP=new Set(['lidl','plus','aktion','angebot','angebote','bio','classic','original','premium','je','pro','packung','pack','pkg','stk','stueck','stück','kg','g','ml','l','gramm','liter','aus','von','mit','und','der','die','das','ein','eine','einer','einem','fuer','für','oesterreich','österreich'])
const BRANDS=new Set(['milbona','freeway','cien','formil','crownfield','freshona','dulano','pikok','favorina','solevita','sole','vita','w5','chefselect','chef','select','fin','carre','finçarre','fin carré','lupilu','esmara','parkside','silvercrest','livarno','floralys','combino','italiamo','deluxe','alesto','mcennedy','vemondo','trattoria','belbake','snackday'])
let volatileState={version:1,offers:[],prices:[],ignored:[],profile:{storeLabel:''},updatedAt:Date.now()}
let storageError='',queued=false
function clone(v){return JSON.parse(JSON.stringify(v))}
function clean(v,max){return String(v==null?'':v).replace(/\s+/g,' ').trim().slice(0,max||200)}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function hash(s){let h=2166136261;for(const ch of String(s||'')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function resolveStorage(){try{const s=root&&root.localStorage;if(!s)throw new Error('Lokaler Speicher nicht verfügbar');const k='nest-lidl-probe-v4';s.setItem(k,'1');if(s.getItem(k)!=='1')throw new Error('Speicherprüfung fehlgeschlagen');s.removeItem(k);return s}catch(e){storageError=String(e&&e.message||e);return{getItem:k=>Object.prototype.hasOwnProperty.call(memory,k)?memory[k]:null,setItem:(k,v)=>{memory[k]=String(v)},removeItem:k=>{delete memory[k]}}}}
const storage=resolveStorage()
function writeVerified(key,value){const text=String(value);storage.setItem(key,text);if(storage.getItem(key)!==text)throw new Error('Lidl-Daten konnten nicht verifiziert werden')}
function today(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addDays(date,days){const d=new Date(String(date).slice(0,10)+'T12:00:00');if(!Number.isFinite(d.getTime()))return date;d.setDate(d.getDate()+days);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function validDate(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(v||'')))return false;const d=new Date(String(v)+'T12:00:00');return Number.isFinite(d.getTime())}
function dateLabel(v,short=false){if(!validDate(v))return'';const d=new Date(v+'T12:00:00');return new Intl.DateTimeFormat('de-AT',short?{day:'2-digit',month:'2-digit'}:{day:'2-digit',month:'short'}).format(d)}
function euro(v){return new Intl.NumberFormat('de-AT',{style:'currency',currency:'EUR'}).format(Number(v)||0)}
function parsePrice(v){if(v==null||v==='')return null;let s=String(v).replace(/\s/g,'').replace(/[^0-9,.-]/g,'');s=s.replace(/^[-][.,]/,'0.').replace(',','.');const n=Math.abs(Number(s));return Number.isFinite(n)?Math.round(n*100)/100:null}
function fold(s){return String(s||'').toLocaleLowerCase('de-AT').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function canonicalToken(token){let t=fold(token);if(!t)return'';const compounds=[['vollmilch','milch'],['haltbarmilch','milch'],['h milch','milch'],['naturjoghurt','joghurt'],['fruchtjoghurt','joghurt'],['jogurt','joghurt'],['yogurt','joghurt'],['haehnchen','huhn'],['hahnchen','huhn'],['huehnchen','huhn'],['cherrytomaten','tomate'],['dattelcherrytomaten','tomate'],['tomaten','tomate'],['gurken','gurke'],['bananen','banane'],['aepfel','apfel'],['apfelsaft','apfel saft'],['vollkornbrot','brot'],['toastbrot','toast'],['mineralwasser','wasser'],['waschmittelcaps','waschmittel'],['cola zero','cola zero']];for(const [from,to] of compounds)if(t.includes(from))t=t.replaceAll(from,to);if(t.length>6&&t.endsWith('en'))t=t.slice(0,-2);else if(t.length>5&&t.endsWith('e'))t=t.slice(0,-1);return t}
function nameTokens(name){const raw=fold(name).split(' ').filter(Boolean),out=[];for(const token of raw){if(STOP.has(token)||BRANDS.has(token)||/^\d+$/.test(token))continue;for(const part of canonicalToken(token).split(' ')){if(part&&part.length>1&&!STOP.has(part)&&!BRANDS.has(part))out.push(part)}}return[...new Set(out)]}
function productKey(name){return nameTokens(name).sort().join(' ')||fold(name).slice(0,80)}
function matchScore(itemName,offerName){const a=nameTokens(itemName),b=nameTokens(offerName);if(!a.length||!b.length)return 0;const ak=a.join(' '),bk=b.join(' ');if(ak===bk)return 1;if((ak.includes(bk)||bk.includes(ak))&&Math.min(ak.length,bk.length)>=4)return .94;let hit=0;for(const x of a)if(b.some(y=>x===y||(x.length>=5&&y.length>=5&&(x.includes(y)||y.includes(x)))))hit++;const recall=hit/a.length,precision=hit/b.length,jacc=hit/(new Set([...a,...b]).size||1);let score=recall*.62+precision*.18+jacc*.20;if(a.length===1&&hit===1)score=Math.max(score,.88);return Math.max(0,Math.min(1,score))}
function parseISOorShort(v,reference=today()){const s=clean(v,20);if(validDate(s))return s;const m=s.match(/^(\d{1,2})\.(\d{1,2})\.(\d{2,4})?$/);if(!m)return'';let year=m[3]?Number(m[3]):Number(reference.slice(0,4));if(year<100)year+=2000;const mm=Number(m[2]),dd=Number(m[1]);let candidate=`${year}-${String(mm).padStart(2,'0')}-${String(dd).padStart(2,'0')}`;if(!m[3]){const ref=new Date(reference+'T12:00:00'),c=new Date(candidate+'T12:00:00'),diff=(c-ref)/86400000;if(diff<-180)candidate=`${year+1}-${String(mm).padStart(2,'0')}-${String(dd).padStart(2,'0')}`;else if(diff>220)candidate=`${year-1}-${String(mm).padStart(2,'0')}-${String(dd).padStart(2,'0')}`}return validDate(candidate)?candidate:''}
function parseRange(text,defaults){const m=String(text||'').match(/(?:in\s+der\s+filiale(?:\s+von)?|gueltig|gültig)(?:\s+ab)?\s*(\d{1,2}\.\d{1,2}\.(?:\d{2,4})?)\s*[-–]\s*(\d{1,2}\.\d{1,2}\.(?:\d{2,4})?)/i);if(!m)return{validFrom:defaults.validFrom,validTo:defaults.validTo};let from=parseISOorShort(m[1],defaults.validFrom),to=parseISOorShort(m[2],from||defaults.validFrom);if(from&&to&&to<from){const y=Number(to.slice(0,4))+1;to=`${y}${to.slice(4)}`}return{validFrom:from||defaults.validFrom,validTo:to||defaults.validTo}}
function normalizeOffer(x,defaults={}){x=x||{};const name=clean(x.name||x.product||x.title,140),price=parsePrice(x.price||x.offerPrice||x.angebotspreis),oldPrice=parsePrice(x.oldPrice||x.regularPrice||x.vorher),validFrom=parseISOorShort(x.validFrom||x.from||defaults.validFrom||today()),validTo=parseISOorShort(x.validTo||x.to||defaults.validTo||addDays(validFrom||today(),7),validFrom||today()),lidlPlus=Boolean(x.lidlPlus||x.plus||/lidl\s*plus/i.test(String(x.badge||''))),unitText=clean(x.unitText||x.unit||x.quantity,90),brand=clean(x.brand,80),source=clean(x.source||defaults.source||'manual',40),sourceUrl=clean(x.sourceUrl||defaults.sourceUrl||SOURCE_URL,500),importedAt=Number(x.importedAt)||Date.now();if(!name||price==null||price<=0)return null;const id=clean(x.id||`lidl_${hash([fold(name),price,validFrom,validTo,lidlPlus].join('|'))}`,90);return{id,name,brand,price,oldPrice:oldPrice&&oldPrice>0?oldPrice:null,unitText,validFrom:validFrom||today(),validTo:validTo||addDays(validFrom||today(),7),lidlPlus,source,sourceUrl,importedAt}}
function defaultState(){return{version:1,offers:[],prices:[],ignored:[],profile:{storeLabel:''},updatedAt:Date.now()}}
function normalizePrice(x){x=x||{};const price=parsePrice(x.price);if(price==null||price<=0)return null;return{id:clean(x.id||`price_${hash(JSON.stringify(x))}`,90),key:clean(x.key||productKey(x.name),120),name:clean(x.name,140),offerName:clean(x.offerName,140),price,date:validDate(x.date)?x.date:today(),offerId:clean(x.offerId,90),createdAt:Number(x.createdAt)||Date.now()}}
function normalizeState(raw){const s=raw&&typeof raw==='object'?raw:{};const offers=Array.isArray(s.offers)?s.offers.map(x=>normalizeOffer(x,{source:'import'})).filter(Boolean):[],prices=Array.isArray(s.prices)?s.prices.map(normalizePrice).filter(Boolean):[],ignored=Array.isArray(s.ignored)?s.ignored.map(x=>clean(x,220)).filter(Boolean).slice(-500):[];return{version:1,offers:offers.slice(-600),prices:prices.slice(-1200),ignored,profile:{storeLabel:clean(s.profile&&s.profile.storeLabel,100)},updatedAt:Number(s.updatedAt)||Date.now()}}
function envelope(state){const clean=normalizeState(state),payload=JSON.stringify(clean);return JSON.stringify({schema:1,release:RELEASE,savedAt:new Date().toISOString(),checksum:hash(payload),state:clean})}
function readBackup(){try{const e=JSON.parse(storage.getItem(BACKUP_KEY)||'null');if(!e||!e.state)return null;const clean=normalizeState(e.state);if(e.checksum&&hash(JSON.stringify(clean))!==e.checksum)return null;return clean}catch{return null}}
function save(next){const clean=normalizeState(next);clean.updatedAt=Date.now();try{writeVerified(STORE_KEY,JSON.stringify(clean));writeVerified(BACKUP_KEY,envelope(clean));volatileState=clone(clean);return clone(clean)}catch(e){storageError=String(e&&e.message||e);volatileState=clone(clean);return clone(clean)}}
function load(){try{const raw=JSON.parse(storage.getItem(STORE_KEY)||'null');if(raw){volatileState=normalizeState(raw);return clone(volatileState)}}catch(e){storageError=String(e&&e.message||e)}const backup=readBackup();if(backup){volatileState=backup;return clone(backup)}return clone(volatileState)}
function offerPhase(offer,on=today()){if(!offer||!validDate(offer.validFrom)||!validDate(offer.validTo))return'expired';if(offer.validFrom<=on&&offer.validTo>=on)return'active';if(offer.validFrom>on&&offer.validFrom<=addDays(on,14))return'upcoming';return offer.validTo<on?'expired':'future'}
function ignoredKey(itemName,offerId){return`${productKey(itemName)}|${offerId}`}
function historyStats(itemName,state=load()){const key=productKey(itemName),rows=state.prices.filter(p=>p.key===key);if(!rows.length)return{count:0,avg:null,min:null,last:null};const sum=rows.reduce((a,p)=>a+p.price,0),sorted=[...rows].sort((a,b)=>b.createdAt-a.createdAt);return{count:rows.length,avg:Math.round(sum/rows.length*100)/100,min:Math.min(...rows.map(p=>p.price)),last:sorted[0].price}}
function ratingForOffer(offer,itemName,state=load()){const hist=historyStats(itemName||offer.name,state),discount=offer.oldPrice&&offer.oldPrice>offer.price?(offer.oldPrice-offer.price)/offer.oldPrice:0;if(hist.count>=2&&hist.min!=null&&offer.price<hist.min-.01)return{level:'top',label:'Tiefstpreis',discount,hist};if(hist.count>=2&&hist.avg&&offer.price<=hist.avg*.85)return{level:'top',label:'Top-Preis',discount,hist};if(discount>=.25)return{level:'top',label:'Top-Preis',discount,hist};if(discount>=.10||(hist.avg&&offer.price<hist.avg*.97))return{level:'offer',label:'Angebot',discount,hist};return{level:'normal',label:'Preis',discount,hist}}
function bestOfferForItem(item,offers,state=load(),includeUpcoming=true){if(!item)return null;const ignored=new Set(state.ignored),candidates=[];for(const offer of offers||state.offers){const phase=offerPhase(offer);if(phase!=='active'&&!(includeUpcoming&&phase==='upcoming'))continue;if(ignored.has(ignoredKey(item.name,offer.id)))continue;const score=matchScore(item.name,offer.name);if(score<.58)continue;candidates.push({offer,score,phase})}candidates.sort((a,b)=>(a.phase==='active'?0:1)-(b.phase==='active'?0:1)||b.score-a.score||a.offer.price-b.offer.price);return candidates[0]||null}
function listMatches(shopState,state=load()){const items=(shopState&&shopState.items||[]).filter(x=>!x.checked),out=[];for(const item of items){const match=bestOfferForItem(item,state.offers,state,true);if(match)out.push({item,...match,rating:ratingForOffer(match.offer,item.name,state)})}return out}
function plannedSummary(shopState,state=load()){const matches=listMatches(shopState,state);let savings=0,offerTotal=0,plus=0;for(const m of matches){const qty=(m.item.unit==='stk'||m.item.unit==='pkg')?Math.max(1,Number(m.item.amount)||1):1,base=m.offer.oldPrice&&m.offer.oldPrice>m.offer.price?m.offer.oldPrice:(m.rating.hist.avg&&m.rating.hist.avg>m.offer.price?m.rating.hist.avg:m.offer.price);offerTotal+=m.offer.price*qty;savings+=Math.max(0,(base-m.offer.price)*qty);if(m.offer.lidlPlus)plus++}return{matches,count:matches.length,savings:Math.round(savings*100)/100,offerTotal:Math.round(offerTotal*100)/100,lidlPlus:plus}}
function rememberPrice(itemName,offer,state=load()){if(!itemName||!offer||offerPhase(offer)!=='active')return state;const key=productKey(itemName),id=`price_${hash([key,today(),offer.id].join('|'))}`;if(state.prices.some(p=>p.id===id))return state;state.prices.push(normalizePrice({id,key,name:itemName,offerName:offer.name,price:offer.price,date:today(),offerId:offer.id,createdAt:Date.now()}));return save(state)}
function mergeOffers(offers,meta={}){let state=load();if(meta.storeLabel!=null)state.profile.storeLabel=clean(meta.storeLabel,100);const map=new Map(state.offers.map(o=>[o.id,o]));for(const raw of offers||[]){const o=normalizeOffer(raw,{validFrom:meta.validFrom,validTo:meta.validTo,source:meta.source||'import',sourceUrl:meta.sourceUrl||SOURCE_URL});if(o)map.set(o.id,o)}state.offers=[...map.values()].filter(o=>o.validTo>=addDays(today(),-31)).sort((a,b)=>a.validFrom.localeCompare(b.validFrom)||a.name.localeCompare(b.name,'de-AT')).slice(-600);return save(state)}
function parseDelimited(text,defaults){const out=[];for(const line of String(text||'').split(/\r?\n/)){const trimmed=line.trim();if(!trimmed)continue;const delim=trimmed.includes('|')?'|':trimmed.includes(';')?';':null;if(!delim)continue;const p=trimmed.split(delim).map(x=>x.trim());if(p.length<2)continue;const o=normalizeOffer({name:p[0],price:p[1],oldPrice:p[2],validFrom:p[3]||defaults.validFrom,validTo:p[4]||defaults.validTo,lidlPlus:/^(1|ja|yes|plus|lidl plus)$/i.test(p[5]||''),unitText:p[6]||'',source:'import'},defaults);if(o)out.push(o)}return out}
function parseLidlText(text,defaults){const raw=String(text||'').replace(/~~/g,'').replace(/\r/g,''),lines=raw.split('\n').map(x=>x.trim()).filter(Boolean),heads=[];for(let i=0;i<lines.length;i++){const m=lines[i].match(/^(.+?)\s+f(?:ü|u)r\s+(-?[\d.,]+)\s*(?:EUR|€)?\s*\*?$/i);if(m)heads.push({i,name:clean(m[1],140),price:parsePrice(m[2])})}const out=[];for(let h=0;h<heads.length;h++){const start=heads[h].i,end=h+1<heads.length?heads[h+1].i:lines.length,block=lines.slice(start,end).join('\n'),old=(block.match(/vorher\s*:?\s*(-?[\d.,]+)\s*€/i)||[])[1],unit=(block.match(/(?:^|\n)Je\s+([^\n]+)/i)||[])[1]||'',range=parseRange(block,defaults),o=normalizeOffer({name:heads[h].name,price:heads[h].price,oldPrice:old,unitText:unit,lidlPlus:/mit\s+lidl\s+plus/i.test(block),validFrom:range.validFrom,validTo:range.validTo,source:'lidl.at',sourceUrl:SOURCE_URL},defaults);if(o)out.push(o)}return out}
function parseImport(text,defaults={}){const d={validFrom:validDate(defaults.validFrom)?defaults.validFrom:today(),validTo:validDate(defaults.validTo)?defaults.validTo:addDays(validDate(defaults.validFrom)?defaults.validFrom:today(),7),sourceUrl:SOURCE_URL};const raw=String(text||'').trim();if(!raw)return[];try{const parsed=JSON.parse(raw),arr=Array.isArray(parsed)?parsed:(Array.isArray(parsed.offers)?parsed.offers:[]);if(arr.length)return arr.map(x=>normalizeOffer(x,d)).filter(Boolean)}catch{}const lidl=parseLidlText(raw,d);if(lidl.length)return lidl;const delimited=parseDelimited(raw,d);if(delimited.length)return delimited;return[]}
function removeOffer(id){const state=load();state.offers=state.offers.filter(o=>o.id!==id);state.ignored=state.ignored.filter(x=>!x.endsWith('|'+id));return save(state)}
function ignoreMatch(itemName,offerId){const state=load(),key=ignoredKey(itemName,offerId);if(!state.ignored.includes(key))state.ignored.push(key);return save(state)}
function resetIgnored(){const state=load();state.ignored=[];return save(state)}
function exportData(){return load()}
function importData(payload){const next=normalizeState(payload&&payload.state?payload.state:payload);return save(next)}
function reset(){storage.removeItem(STORE_KEY);storage.removeItem(BACKUP_KEY);volatileState=defaultState();return true}
function status(){const state=load(),phases=state.offers.reduce((a,o)=>(a[offerPhase(o)]=(a[offerPhase(o)]||0)+1,a),{});return{available:!storageError,persistent:!storageError,lastError:storageError,release:RELEASE,storeKey:STORE_KEY,offers:state.offers.length,active:phases.active||0,upcoming:phases.upcoming||0,prices:state.prices.length,storeLabel:state.profile.storeLabel}}
function getShopState(){try{return Shop?Shop.load():{items:[]}}catch{return{items:[]}}}
function showToast(message,bad=false){if(!root.document)return;const t=root.document.getElementById('toast');if(!t)return;t.textContent=message;t.classList.toggle('bad',!!bad);t.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>t.classList.remove('show','bad'),2300)}
function refreshApp(){try{root.NestAppV3&&root.NestAppV3.render&&root.NestAppV3.render(false)}catch(e){console.error(e)}setTimeout(scheduleUI,20)}
function shopCategory(name){try{return Shopping&&Shopping.inferCategory?Shopping.inferCategory(name,''):'Sonstiges'}catch{return'Sonstiges'}}
function addOfferToList(offer){if(!Shop)throw new Error('Einkaufsspeicher nicht verfügbar');const shop=Shop.load(),exists=shop.items.some(it=>!it.checked&&matchScore(it.name,offer.name)>=.9);if(exists){showToast('Produkt ist bereits auf deiner Liste');return}Shop.addManual({name:offer.name,amount:1,unit:'stk',category:shopCategory(offer.name),note:`Lidl Angebot · ${euro(offer.price)} · bis ${dateLabel(offer.validTo,true)}`});refreshApp();showToast('Zur Einkaufsliste hinzugefügt')}
function dialog(){if(!root.document)return null;let d=root.document.getElementById('v4LidlDialog');if(!d){d=root.document.createElement('dialog');d.id='v4LidlDialog';d.className='v4-lidl-dialog';root.document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d)d.close()})}return d}
function sourceButton(){return`<button type="button" class="v4-secondary" data-v4="source">Lidl.at öffnen</button>`}
function offerCard(m,state){const offer=m.offer||m,item=m.item||null,rating=m.rating||ratingForOffer(offer,item&&item.name,state),phase=m.phase||offerPhase(offer),hist=rating.hist,history=hist.count?`<span>Ø ${euro(hist.avg)}${hist.min!=null?` · Tief ${euro(hist.min)}`:''}</span>`:'',old=offer.oldPrice&&offer.oldPrice>offer.price?`<del>${euro(offer.oldPrice)}</del>`:'',plus=offer.lidlPlus?'<span class="v4-plus-badge">Lidl Plus</span>':'',when=phase==='upcoming'?`ab ${dateLabel(offer.validFrom)}`:`bis ${dateLabel(offer.validTo)}`,match=item?`<div class="v4-match-line"><span>Passt zu <b>${esc(item.name)}</b></span><button type="button" data-v4="ignore" data-item="${esc(item.name)}" data-id="${esc(offer.id)}">Nicht passend</button></div>`:'',action=item?'<span class="v4-on-list">Auf deiner Liste</span>':`<button type="button" class="v4-add" data-v4="add" data-id="${esc(offer.id)}">+ Einkaufsliste</button>`;return`<article class="v4-offer-card ${rating.level} ${phase}"><div class="v4-offer-top"><div><span class="v4-rating">${esc(rating.label)}</span>${plus}</div><button type="button" class="v4-remove" data-v4="remove" data-id="${esc(offer.id)}" aria-label="Angebot entfernen">×</button></div><h3>${esc(offer.name)}</h3><div class="v4-price"><strong>${euro(offer.price)}</strong>${old}<small>${esc(offer.unitText||'')}</small></div><div class="v4-offer-meta"><span>${esc(when)}</span>${history}</div>${match}<div class="v4-card-action">${action}</div></article>`}
function visibleOffers(state){return state.offers.filter(o=>['active','upcoming'].includes(offerPhase(o)))}
function renderHub(){const d=dialog();if(!d)return;const state=load(),shop=getShopState(),summary=plannedSummary(shop,state),relevant=summary.matches,used=new Set(relevant.map(m=>m.offer.id)),active=state.offers.filter(o=>offerPhase(o)==='active'&&!used.has(o.id)),upcoming=state.offers.filter(o=>offerPhase(o)==='upcoming'&&!used.has(o.id)),sections=[];if(relevant.length)sections.push(`<section class="v4-section"><header><div><span>FÜR DEINE LISTE</span><h3>${relevant.length} passende ${relevant.length===1?'Aktion':'Aktionen'}</h3></div>${summary.savings>0?`<strong>ca. ${euro(summary.savings)} sparen</strong>`:''}</header><div class="v4-offer-grid">${relevant.map(m=>offerCard(m,state)).join('')}</div></section>`);if(active.length)sections.push(`<section class="v4-section"><header><div><span>DIESE WOCHE</span><h3>Weitere Angebote</h3></div></header><div class="v4-offer-grid">${active.map(o=>offerCard(o,state)).join('')}</div></section>`);if(upcoming.length)sections.push(`<section class="v4-section"><header><div><span>DEMNNÄCHST</span><h3>Nächste Angebote</h3></div></header><div class="v4-offer-grid">${upcoming.map(o=>offerCard(o,state)).join('')}</div></section>`);if(!sections.length){openImport();return}d.innerHTML=`<section class="v4-hub"><header class="v4-hub-head"><div><span>NEST · V${RELEASE}</span><h2>Lidl Angebote</h2>${state.profile.storeLabel?`<small>${esc(state.profile.storeLabel)}</small>`:''}</div><button type="button" class="v4-close" data-v4="close">×</button></header>${summary.count?`<div class="v4-summary"><div><strong>${summary.count}</strong><span>für deine Liste</span></div>${summary.savings>0?`<div><strong>${euro(summary.savings)}</strong><span>geschätzt gespart</span></div>`:''}${summary.lidlPlus?`<div><strong>${summary.lidlPlus}</strong><span>Lidl Plus</span></div>`:''}</div>`:''}<div class="v4-toolbar"><button type="button" class="v4-primary" data-v4="import">Angebote importieren</button>${sourceButton()}</div>${sections.join('')}<footer class="v4-hub-foot"><button type="button" data-v4="clear-ignored">Zuordnungen zurücksetzen</button><button type="button" data-v4="clear-offers">Angebote löschen</button></footer></section>`;if(!d.open)d.showModal()}
function openImport(){const d=dialog();if(!d)return;const state=load(),from=today(),to=addDays(from,7);d.innerHTML=`<form class="v4-import" data-v4-form="import"><header class="v4-hub-head"><div><span>NEST · V${RELEASE}</span><h2>Lidl Angebote importieren</h2></div><button type="button" class="v4-close" data-v4="close">×</button></header><div class="v4-import-body"><label class="v4-field"><span>Filiale / Ort <small>optional</small></span><input name="storeLabel" maxlength="100" value="${esc(state.profile.storeLabel||'')}"></label><div class="v4-date-grid"><label class="v4-field"><span>Gültig von</span><input name="validFrom" type="date" value="${from}" required></label><label class="v4-field"><span>Gültig bis</span><input name="validTo" type="date" value="${to}" required></label></div><label class="v4-field"><span>Angebote einfügen</span><textarea name="payload" rows="9" placeholder="Text von Lidl.at hier einfügen …\n\nOder pro Zeile:\nMilch | 0,99 | 1,39 | 2026-08-10 | 2026-08-12 | plus"></textarea></label><div class="v4-import-actions"><button type="button" data-v4="clipboard">Aus Zwischenablage</button><button type="button" data-v4="manual">Ein Angebot manuell</button></div><p class="v4-help">NEST akzeptiert kopierten Lidl.at-Text, JSON sowie Zeilen mit Produkt | Preis | alter Preis | von | bis | Lidl Plus.</p></div><footer class="v4-form-foot">${sourceButton()}<button type="submit" class="v4-primary">Importieren</button></footer></form>`;if(!d.open)d.showModal()}
function openManual(){const d=dialog();if(!d)return;const state=load(),from=today(),to=addDays(from,7);d.innerHTML=`<form class="v4-import" data-v4-form="manual"><header class="v4-hub-head"><div><span>NEST · V${RELEASE}</span><h2>Angebot hinzufügen</h2></div><button type="button" class="v4-close" data-v4="close">×</button></header><div class="v4-import-body"><label class="v4-field"><span>Produkt</span><input name="name" required maxlength="140"></label><div class="v4-date-grid"><label class="v4-field"><span>Angebotspreis</span><input name="price" type="number" min="0.01" step="0.01" required inputmode="decimal"></label><label class="v4-field"><span>Alter Preis <small>optional</small></span><input name="oldPrice" type="number" min="0.01" step="0.01" inputmode="decimal"></label></div><label class="v4-field"><span>Packung / Einheit <small>optional</small></span><input name="unitText" maxlength="90" placeholder="z. B. Je 1 l"></label><div class="v4-date-grid"><label class="v4-field"><span>Gültig von</span><input name="validFrom" type="date" value="${from}" required></label><label class="v4-field"><span>Gültig bis</span><input name="validTo" type="date" value="${to}" required></label></div><label class="v4-checkline"><input name="lidlPlus" type="checkbox"><span>Lidl Plus Angebot</span></label><label class="v4-field"><span>Filiale / Ort <small>optional</small></span><input name="storeLabel" maxlength="100" value="${esc(state.profile.storeLabel||'')}"></label></div><footer class="v4-form-foot"><button type="button" data-v4="import">Zurück</button><button type="submit" class="v4-primary">Angebot speichern</button></footer></form>`;if(!d.open)d.showModal()}
function enhanceShopping(){if(!root.document||!Shop)return;const main=root.document.querySelector('.v3-main[data-page="shopping"]');if(!main)return;const state=load(),shop=getShopState(),summary=plannedSummary(shop,state);let entry=main.querySelector('.v4-lidl-entry');if(!entry){entry=root.document.createElement('button');entry.type='button';entry.className='v4-lidl-entry';entry.dataset.v4='open';main.insertBefore(entry,main.firstChild)}const current=visibleOffers(state).length,sub=summary.count?`${summary.count} ${summary.count===1?'Treffer':'Treffer'} für deine Liste${summary.savings>0?` · ca. ${euro(summary.savings)} sparen`:''}`:(current?`${current} aktuelle / kommende Angebote`:'Angebote importieren');entry.innerHTML=`<span class="v4-lidl-mark">L</span><span class="v4-entry-copy"><b>Lidl Angebote</b><small>${esc(sub)}</small></span><span class="v4-entry-chev">›</span>`;const byId=new Map((shop.items||[]).map(it=>[String(it.id),it]));main.querySelectorAll('.v3-shop-row').forEach(row=>{const id=row.querySelector('[data-v3="shop-toggle"]')?.dataset.id,item=byId.get(String(id||'')),mainBtn=row.querySelector('.v3-shop-main');if(!item||!mainBtn)return;const old=mainBtn.querySelector('.v4-shop-offer'),match=bestOfferForItem(item,state.offers,state,true);if(!match){if(old)old.remove();return}const label=match.phase==='active'?'Lidl Angebot':`ab ${dateLabel(match.offer.validFrom,true)}`,plus=match.offer.lidlPlus?' · Plus':'';let pill=old;if(!pill){pill=root.document.createElement('span');pill.className='v4-shop-offer';mainBtn.appendChild(pill)}pill.className=`v4-shop-offer ${match.phase}`;pill.innerHTML=`<b>${euro(match.offer.price)}</b><span>${esc(label+plus)}</span>`})}
function release(){if(!root.document)return;root.document.title='NEST 4';root.document.documentElement.dataset.nestRelease=RELEASE;const meta=root.document.querySelector('meta[name="nest-version"]');if(meta)meta.content=RELEASE;const top=root.document.querySelector('.v3-top>div>span');if(top&&top.textContent!=='NEST · V'+RELEASE)top.textContent='NEST · V'+RELEASE}
function enhanceUI(){queued=false;release();enhanceShopping()}
function scheduleUI(){if(queued||!root.document)return;queued=true;(root.requestAnimationFrame||setTimeout)(enhanceUI)}
function handleClick(e){const b=e.target.closest&&e.target.closest('[data-v4]');if(b){const action=b.dataset.v4,id=b.dataset.id,d=dialog();if(action==='open')renderHub();else if(action==='close')d&&d.close();else if(action==='import')openImport();else if(action==='manual')openManual();else if(action==='source'){try{root.open(SOURCE_URL,'_blank','noopener,noreferrer')}catch{}}else if(action==='add'){const state=load(),offer=state.offers.find(o=>o.id===id);if(offer)addOfferToList(offer)}else if(action==='remove'){removeOffer(id);renderHub();scheduleUI()}else if(action==='ignore'){ignoreMatch(b.dataset.item,id);renderHub();scheduleUI();showToast('Zuordnung wird nicht mehr verwendet')}else if(action==='clear-ignored'){resetIgnored();renderHub();scheduleUI();showToast('Zuordnungen zurückgesetzt')}else if(action==='clear-offers'){if(root.confirm&&root.confirm('Alle importierten Lidl-Angebote löschen?')){const state=load();state.offers=[];state.ignored=[];save(state);d&&d.close();scheduleUI();showToast('Angebote gelöscht')}}else if(action==='clipboard'){root.navigator&&root.navigator.clipboard&&root.navigator.clipboard.readText().then(text=>{const ta=d&&d.querySelector('textarea[name="payload"]');if(ta)ta.value=text}).catch(()=>showToast('Zwischenablage konnte nicht gelesen werden',true))}return}const toggle=e.target.closest&&e.target.closest('[data-v3="shop-toggle"]');if(toggle&&Shop){const id=toggle.dataset.id;setTimeout(()=>{try{const shop=Shop.load(),item=shop.items.find(x=>String(x.id)===String(id));if(!item||!item.checked)return;const state=load(),match=bestOfferForItem(item,state.offers,state,false);if(match&&match.phase==='active'){rememberPrice(item.name,match.offer,state);scheduleUI()}}catch(err){console.error(err)}},20)}}
function handleSubmit(e){const form=e.target.closest&&e.target.closest('form[data-v4-form]');if(!form)return;e.preventDefault();const d=new FormData(form);try{if(form.dataset.v4Form==='import'){const validFrom=String(d.get('validFrom')||today()),validTo=String(d.get('validTo')||addDays(validFrom,7));if(!validDate(validFrom)||!validDate(validTo)||validTo<validFrom)throw new Error('Bitte gültigen Zeitraum wählen');const offers=parseImport(String(d.get('payload')||''),{validFrom,validTo});if(!offers.length)throw new Error('Keine Angebote erkannt. Nutze Lidl.at-Text, JSON oder Produkt | Preis | …');mergeOffers(offers,{validFrom,validTo,storeLabel:String(d.get('storeLabel')||''),source:'import',sourceUrl:SOURCE_URL});showToast(`${offers.length} ${offers.length===1?'Angebot':'Angebote'} importiert`);renderHub();scheduleUI()}else if(form.dataset.v4Form==='manual'){const offer=normalizeOffer({name:d.get('name'),price:d.get('price'),oldPrice:d.get('oldPrice'),unitText:d.get('unitText'),validFrom:d.get('validFrom'),validTo:d.get('validTo'),lidlPlus:d.get('lidlPlus')==='on',source:'manual',sourceUrl:SOURCE_URL});if(!offer)throw new Error('Bitte Produkt und Preis prüfen');mergeOffers([offer],{storeLabel:String(d.get('storeLabel')||'')});showToast('Angebot gespeichert');renderHub();scheduleUI()}}catch(err){console.error(err);showToast(err.message||'Angebote konnten nicht gespeichert werden',true)}}
function init(){if(!root.document)return;const app=root.document.getElementById('app');if(app)new MutationObserver(scheduleUI).observe(app,{childList:true});root.document.addEventListener('click',handleClick,false);root.document.addEventListener('submit',handleSubmit,true);root.addEventListener&&root.addEventListener('pageshow',scheduleUI);root.addEventListener&&root.addEventListener('storage',e=>{if(e.key===STORE_KEY||e.key===(Shopping&&Shopping.STORE_KEY))scheduleUI()});if(root.document.readyState==='loading')root.document.addEventListener('DOMContentLoaded',scheduleUI,{once:true});else scheduleUI();setTimeout(scheduleUI,120);setTimeout(scheduleUI,700)}
const API={RELEASE,STORE_KEY,BACKUP_KEY,SOURCE_URL,load,save,reset,status,exportData,importData,parseImport,parseLidlText,parseDelimited,normalizeOffer,productKey,matchScore,offerPhase,bestOfferForItem,listMatches,plannedSummary,ratingForOffer,historyStats,rememberPrice,mergeOffers,ignoreMatch,resetIgnored,open:renderHub,openImport,enhance:scheduleUI}
init()
return API
})
