import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const index=await readFile(new URL('../public/index.html',import.meta.url),'utf8');const app=await readFile(new URL('../public/app.js',import.meta.url),'utf8');const css=await readFile(new URL('../public/styles.css',import.meta.url),'utf8');const manifest=JSON.parse(await readFile(new URL('../public/manifest.webmanifest',import.meta.url),'utf8'));const icon=await readFile(new URL('../public/icon.svg',import.meta.url),'utf8');
test('V19.2 uses the professional HaushaltKlar brand consistently',()=>{assert.equal(manifest.name,'HaushaltKlar');assert.equal(manifest.short_name,'HaushaltKlar');assert.equal(manifest.id,'haushaltklar-household-app');assert.match(index,/<title>HaushaltKlar<\/title>/);assert.match(index,/apple-mobile-web-app-title" content="HaushaltKlar/);assert.match(app,/APP_BRAND_V192 = 'HaushaltKlar'/);});
test('V19.2 boot screen is branded and contains no fake status data',()=>{assert.match(index,/boot-screen-v192/);assert.match(index,/Organisiert\. Entspannt\. Zuhause\./);assert.match(css,/\.boot-brand-mark-v192/);assert.doesNotMatch(index,/5G|battery|21:28|9:41/);});
test('V19.2 navigation is compact, floating and six-tab safe',()=>{assert.match(css,/\.tab-bar-six-v19[\s\S]*grid-template-columns:\s*repeat\(6/);assert.match(css,/height:\s*54px/);assert.match(css,/border-radius:\s*19px/);assert.match(css,/\.tab-button\.active \.tab-icon/);assert.match(css,/safe-bottom/);});
test('V19.2 dashboard uses actual household data and no sample cards',()=>{assert.match(app,/renderDashboardV192/);assert.match(app,/data\.summary\.remaining/);assert.match(app,/dashboardMealsV192/);assert.match(app,/data\?\.notes/);assert.doesNotMatch(app,/Guten Morgen, Lisa/);});
test('new icon contains a house and checkmark vector',()=>{assert.match(icon,/M258 485 512 278l254 207/);assert.match(icon,/m410 608 72 72 143-151/);assert.match(icon,/linearGradient id="brand"/);});
